### ISSUE TITLE
Istanbul/coverage reporter generate LCOV file with relative path for SF parameter instead of absolute path

### ISSUE THREAD

**Issue by flambert70** [gotwarlost/istanbul#104]
We are using Istanbul with Karma to generate a javascript code coverage report. We are using "lcovonly" option for the reporter type.
At present, the file generated by Karma/Istanbul contains a relative path for the SF parameter of lcov.info while it must be an absolute path. (see http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php)
This is causing problems when we try to read this lcov file with sonar javascript plugin because the source files are not found.

We finally end to "patch" some source files of istanbul in order to fix this problem for lcovonly, but I think this should be done for lcov also.
What modifications ?
1) /usr/lib/node_modules/karma-coverage/node_modules/istanbul/lib/report/lcov.js

```
 29 function LcovReport(opts) {
 30     Report.call(this);
 31     opts = opts || {};
 32     var baseDir = path.resolve(opts.dir || process.cwd()),
 33         htmlDir = path.resolve(baseDir, 'lcov-report');
 34     //patch
 35     var rootDir = path.resolve(opts.root || process.cwd());
 36     mkdirp.sync(baseDir);
 37     //patch
 38     //this.lcov = new LcovOnlyReport({ dir: baseDir });
 39     this.lcov = new LcovOnlyReport({ dir: baseDir, root: rootDir });
 40     this.html = new HtmlReport({ dir: htmlDir, sourceStore: opts.sourceStore});
 41 }
```

2) /usr/lib/node_modules/karma-coverage/node_modules/istanbul/lib/report/lcovonly.js

```
 function LcovOnlyReport(opts) {
 27     this.opts = opts || {};
 28     this.opts.dir = this.opts.dir || process.cwd();
 29     this.opts.writer = this.opts.writer || null;
 30     //patch
 31     this.opts.root = this.opts.root || process.cwd();
 32 }
...
 45         writer.println('TN:'); //no test name
 46         //patch
 47         //writer.println('SF:' +fc.path);
 48         writer.println('SF:' + this.opts.root + fc.path.replace(/\./,''));
```

This way lcov file generated has absolute path for SF in lcov.info.

Could this be taken into account for the next version of Istanbul. It will save us a lot of time ? I don't think it is a big fix.

This bug is similar to https://github.com/karma-runner/karma/issues/528, but was not fixed.

**Comment by pocesar** [comment]
seems to be a problem again yeah

**Comment by vptech20nn** [comment]
Facing same issue, are there workarounds so that lcov.info has relative paths instead?

**Comment by rogerpadilla** [comment]
+1 for using absolute paths (sonarqube expects that).

**Comment by vladistan** [comment]
+1

For sonarqube I use a dirty hack by running this sed command

`sed  -i.bak  's@^SF:/app/@SF:@' coverage/lcov.info`

in between the unit tests and sonar scan.

Because my build runs in docker container I can get away with hard-coding absolute path /app

**Comment by RobotLimeLtd** [comment]
-1 for absolute paths.  Sonar works regardless, but with absolute paths, you're stuck with an lcov.info file that can only be used in one location.  My build pipeline zips up enough of the current working build directory so I can run the Sonar analysis in a complete independent build job.  The absolute paths make this impossible, as they point to a specific build directory path.

**Comment by RachelSatoyama** [comment]
I don't quite get why sonarqube expects absolute paths. We can run tests on one job on some machine and ran report analysis on some different machine. Absolute paths are acceptable in some cases but in some others they definitely are not.

**Comment by benjamine** [comment]
+1 for having an option to choose between absolute and relative

**Comment by miguelrincon** [comment]
@benjamine and @gotwarlost I have sent a PR requesting with precisely this feature. I hope to revisit this topic.

**Comment by MuraliM** [comment]
@vladistan I need to make a similar thing for teamcity. Is there any command like sed available for teamcity? I tried the below but no impact 

```
$workdir="%teamcity.build.checkoutDir%"
sed -i -- 's/\/$workdir/Web.Spa/app/g' coverage/report/lcov.info
```
**Same Lcov** with absolute path

TN:
SF:**E:\a03\work\bb52cb33e083fc9\src\**Web.Spa\app\History\history.service.js
FN:5,(anonymous_1)
FN:6,HistoryService
FN:8,(anonymous_3)
FN:9,(anonymous_4)

**Comment by michael-mckenna** [comment]
To provide another example passed off @vladistan 's logic:

```
  pattern="/usr/src/app/"
  replacement="output/myName/src/app"
  sed -i "s@$pattern@$replacement@g" output/coverage/lcov.info
```

I'm adding this in the execute shell phase in the "Build" phase in jenkins.

**Comment by jsmithe** [comment]
Is there another way to get relative paths now?

Our build is within a docker container separate from where analysis are run which is failing because it cannot find the JS files.

**Comment by donmahallem** [comment]
It would be great if there was a way to have an option to toggle which behavior we want. Relative as default and absolute as option.
