### ISSUE TITLE
testing requirejs moduels with Mocha, getting: "No coverage information was collected, exit without writing coverage information"

### ISSUE THREAD

**Issue by attodorov** [gotwarlost/istanbul#125]
I use Mocha (1.15.1) & Istanbul 0.1.46. I have a webp app and i am unit testing some modules with Mocha in the following way - the module under test is loaded using Node's Requirejs - it's a requirejs module which is pure javascript and doesn't use jQuery, ajax or any kind of DOM API: 
# 

var assert = require("chai").assert;
var expect = require("chai").expect;
var should = require("chai").should();
var chai = require("chai");

var requirejs = require("requirejs");

var myModule = requirejs("myModule");

requirejs.config({
        nodeRequire: require,
        baseUrl: "./src/js"
});

describe("tests for myModule", function () { 
# 

but it just doesn't seem to work. I've tried running various commands, for example:

istanbul cover node_modules/mocha/bin/_mocha -- -R spec

and 

istanbul cover _mocha -- -R spec 

have tried having instanbul installed both locally & globally

no luck. What is get is:

No coverage information was collected, exit without writing coverage information

But all tests  for "myModule" run successfully. 

What am i doing wrong? is this scenario supported in istanbul? Btw, if i instrument my code with jscoverage and then run it with mocha, it works fine. But not with istanbul. Note that i am not instrumenting anything manually.

Thanks very much.

**Comment by kumar-utsav** [comment]
I have tried running all the commands listed above but I am still getting "No coverage information was collected, exit without writing coverage information"

**Comment by jotaoncode** [comment]
@kumar-utsav  Iam running the same problem here, looks like this is an example of lcov working ok:

https://github.com/nwood888/istanbul-harmony-example

I am still playing a bit to make it work for me. Have a good day.

**Comment by bendly** [comment]
`istanbul cover _mocha test/**/*.js`

Finally I found the above line work for me, anyone know why or how we could remove explicitly tell the files to be tested?
