### ISSUE TITLE
Istanbul hangs when using OSX Mavericks

### ISSUE THREAD

**Issue by cressie176** [gotwarlost/istanbul#133]
I'm trying to get istanbul working with [yadda](http://github.com/acuminous/yadda) but when I try running ```istanbul cover _mocha``` the process never returns. A coverage directory is created but it's empty.

I get the same problem if I create a simple test.js with nothing more than a console.log and do ```istanbul cover test.js```

OSX Mavericks
Istanbul 0.2.3
Node v0.10.22

Any ideas?

**Comment by popomore** [comment]
Fix of Glob work for me, @gotwarlost can you upgrade to the lastest version?

**Comment by popomore** [comment]
@mklabs

**Comment by mklabs** [comment]
thanks @popomore 

Hello @gotwarlost Do you still support node 0.8 ? I'm working on node-fileset 0.2.x versions and will most likely drop support to 0.8

**Comment by davglass** [comment]
I don't think that we should support Node 0.8.x.

**Comment by mklabs** [comment]
Thanks @davglass I think so too. It really ease the process for me, node-glob also only supports iojs, 0.10 and 0.12: https://github.com/isaacs/node-glob/blob/master/.travis.yml
