### ISSUE TITLE
istanbul don't include unrequired JS files in coverage

### ISSUE THREAD

**Issue by amoufaddel** [gotwarlost/istanbul#142]
Hello,
In my nodeJS application, i have this package for DAO:
- api/dao/ClasseA.js
- api/dao/ClasseB.js

and this package for unit test with mocha:
- test/dao/testA.js  that require just ClasseA.js.

I use this command to execute tests for testA.js and generate Cobertura report :
istanbul cover --report cobertura mocha  test/dao/*.js 
It's work fine, But the coverage report don't include ClasseB.js in coverage. 
Any ideas?.

**Comment by aggieben** [comment]
Is there a way to do `--include-all-sources` and have it respect the default excludes?  When I do this, istanbul tries to instrument everything in `node_modules` and fails on esprima.js.

**Comment by juancarlosfarah** [comment]
I'm running into the same issue as @aggieben. Anyone recommend a way around this?

**Comment by awolden** [comment]
We really need the ability to include only certain files when we use `--include-all-sources`. I have the same issue as @aggieben and @juancarlosfarah.

```
./node_modules/istanbul/node_modules/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 1: Unexpected token (
    at constructError (./node_modules/istanbul/node_modules/esprima/esprima.js:2406:21)
    at createError (./node_modules/istanbul/node_modules/esprima/esprima.js:2425:17)
..........
```

**Comment by mike-goodwin** [comment]
+1 for the suggestion from @aggieben, @juancarlosfarah  and @awolden 
When I use `--include-all-sources` it does literally ALL sources including default excludes and explicit excludes using` -x`.In my case this leads to a process out of memory error.

**Comment by abritinthebay** [comment]
Agreed, the same problem here. This STRONGLY needs to be reopened.

**Comment by shaikhspear16** [comment]
facing a similar problem, with ionic 2 angular 2 ts karma jasmine remap-istanbul

not able to get files for which spec is not written covered in code coverage


my karma.config.json

`module.exports = function(config) {
    config.set({

        basePath: '.',

        frameworks: ['jasmine'],

        files: [
            // paths loaded by Karma
            {pattern: 'node_modules/angular2/bundles/angular2-polyfills.js', included: true, watched: true},
            {pattern: 'node_modules/systemjs/dist/system.src.js', included: true, watched: true},
            {pattern: 'node_modules/rxjs/bundles/Rx.js', included: true, watched: true},
            {pattern: 'node_modules/angular2/bundles/angular2.dev.js', included: true, watched: true},
            {pattern: 'node_modules/angular2/bundles/testing.dev.js', included: true, watched: true},
            {pattern: 'node_modules/angular2/bundles/http.dev.js', included: true, watched: true},
            {pattern: 'karma-test-shim.js', included: true, watched: true},

            // paths loaded via module imports
            {pattern: 'dist/**/*.js', included: true, watched: true},

            // paths to support debugging with source maps in dev tools
            {pattern: 'src/**/*.ts', included: false, watched: false},
            {pattern: 'dist/**/*.js.map', included: false, watched: false}
        ],

        // proxied base paths
        proxies: {
            // required for component assests fetched by Angular's compiler
            '/src/': '/base/src/'
        },

        port: 9876,

        logLevel: config.LOG_INFO,

        colors: true,

        autoWatch: true,

        browsers: ['Chrome'],

        // Karma plugins loaded
        plugins: [
            'karma-jasmine',
            'karma-coverage',
            'karma-chrome-launcher'
        ],

        // Coverage reporter generates the coverage
        reporters: ['progress', 'dots', 'coverage'],

        // Source files that you wanna generate coverage for.
        // Do not include tests or libraries (these files will be instrumented by Istanbul)
        preprocessors: {
            'dist/**/!(*spec).js': ['coverage']
        },

        coverageReporter: {
            reporters:[
                {type: 'json', subdir: '.', file: 'coverage-final.json'}
            ]
        },

        singleRun: true
    })
};
`

Any Help or work around ?
I am new to this framework !!
Thank You

**Comment by sandy-adi** [comment]
using `--include-all-sources` option works, but it appears like having it in `.istanbul.yml` is not making a difference

**Comment by sandy-adi** [comment]
try this: add the following to your `.istanbul.yml` worked for me
```
instrumentation:
   include-all-sources: true
```

**Comment by jedwards1211** [comment]
As long as code in the untested modules runs without crashing, I'd say the extra coverage from that is valid.

**Comment by jedwards1211** [comment]
@jsdevel I don't think requiring the missing files is hackish, what you're testing in that case is that any code that runs when otherwise untested modules are required doesn't throw an error.
