### ISSUE TITLE
adding coverage report for node cluster & cluster.fork()

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#147]
I've managed to add coverage to child processes by using

``` js

function spawnChild(execPath, args) {
    /*jshint camelcase: false */
    var isIstanbul = process.env.running_under_istanbul;

    if (isIstanbul) {
        var fileName = args[0];
        var rest = args.slice(1);
        args = [
            'node_modules/.bin/istanbul',
            'cover',
            fileName,
            '--report',
            'none',
            '--dir',
            './coverage/' + path.basename(fileName, '.js'),
            '--'
        ].concat(rest);
    }

    return spawn(execPath, args);
}
```

This works great for getting code coverage for the master process of the Application i'm spawning for my integration tests.

However my application spawns workers with `cluster.fork()`

I'm not sure how to get instanbul to add coverage to worker processes.

Any suggestions ?

**Comment by silkentrance** [comment]
@Raynos please have a look at https://github.com/raszi/node-tmp and the way we handle gathering test coverage from multiple processes. While we are not doing this in "parallel" right now, the implemented mechanisms should suffice.

@gotwarlost basically a usage issue. Perhaps an FAQ would be required?

@gotwarlost is this by any chance a duplicate of #148

**Comment by Raynos** [comment]
There's another tool that instruments child processes for tests ( https://github.com/istanbuljs/nyc )
