### ISSUE TITLE
timestamp or uuid the coverage directory

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#148]
To support having multiple calls to `istanbul cover` in parallel writing to the same location we would need to append some noise to the end of the filename.

This would allow me to spawn the same thing in parallel for my tests and gathering all the coverage reports.

However because the file names are random, I as a user of istanbul would have to `rm -rf  ./coverage` before every run of my covered tests to GC these old files.

This allows me to transparently add coverage to node's `require('cluster')` with the caveat that I have to add `rm -rf ./coverage` to my `npm run cover` command

**Comment by silkentrance** [comment]
@Raynos please have a look at https://github.com/raszi/node-tmp and the way we handle gathering test coverage from multiple processes. While we are not doing this in "parallel" right now, the implemented mechanisms should suffice.

@gotwarlost basically a usage issue. Perhaps an FAQ would be required?
