### ISSUE TITLE
Add some user flexibility for branch coverage stats

### ISSUE THREAD

**Issue by gotwarlost** [gotwarlost/istanbul#15]
@davglass @reid @mfncooper @sdesai

Starting this thread to see how we can improve branch coverage in Istanbul.

Assumption: Default processing is just about ok in the sense of generality and hitting the cases we care about. If not, let me know.

Based on conversations with some of you here are some desires:
1. Ability to automatically exclude generally-impossible-to-test-without-a-lot-of-shennanigans branches. The big one here is `if (object.hasOwnProperty('foo')) {}` style branches where the else path should be considered non-existent and istanbul should probably not even consider this `if` statement as a branch.
2. Ability for user to tag certain branches as unimportant/ untestable. Potential implementation is via comments just before the line of code (similar to jslint). Feel free to send thoughts on what this interface should look like.
3. Ability to specify a reason along with the comment that is somehow shown in the HTML report
4. Ability (for managers) to ensure that people aren't commenting their way out of their responsibilities (perhaps by having "raw" numbers shown against the "processed" numbers when different?)

Anyway, ideas welcome. Just keep this issue updated and we can circle back 3-4 weeks from now and decide what needs to be done. I'll also need to do some research on how comments are made available in the parse tree by esprima before we decide the final solution.

**Comment by FlorianLoch** [comment]
Are there any future plans to implement a (cli) switch to ignore all missing else-branches?

**Comment by gotwarlost** [comment]
No. Why do you need this?

**Comment by anobika** [comment]
I have code that has multiple if statements which have no corresponding else statements. I have been adding /* istanbul ignore else */ individually for all these if statements in order to ignore the corresponding missing else statements. Is there are way to ignore all the missing else statements with a single comment?

**Comment by FlorianLoch** [comment]
The case @anobika mentioned would be a use case for this feature. 
I am needing such a feature because I am instrumenting huge amounts of code I do not control and adding these "ignore-comments" would need me to add another "parse+walk AST+generate code" step in front of using great Istanbul for instrumentation.

**Comment by pdrozdowski** [comment]
Hi, marking with comment parts of code to ignore in test coverage would be super useful. In my scenario i'm having code 100% in typescript and so there are bits of code added from compiler which will not get into cover - for instance there is an if in --extend method added each time you are using inheritance in code and there is no way to test that. regards.

**Comment by ashishdasnurkar** [comment]
+1 for adding a a cli switch to ignore all "missing" else branches

**Comment by deckar01** [comment]
@FlorianLoch @pdrozdowski @ashishdasnurkar Is there a reason you are not testing to make sure the code inside the `if` block is not executed when the condition is false?

```js
function foo(bar) {
  if(bar) {
    baz();
  }
}
```

should have 2 tests:

```js
var bar = true;
foo(bar);
expect(bar).toHaveBeenCalled();
```

and

```js
var bar = false;
foo(bar);
expect(bar).not.toHaveBeenCalled();
```

to protect against future changes like

```js
function foo(bar) {
  baz();
}
```

**Comment by FlorianLoch** [comment]
@deckar01 Perhaps I got you wrong but as I mentioned I do noz control the code that shall be instrumented so I see no way to pick up your suggestion without the former mentioned parse-walkAST-generate step which I definitely want to avoid due to various reasons.

**Comment by deckar01** [comment]
@FlorianLoch I would recommend something like https://github.com/douglasduteil/isparta if the code is generated. Completely ignoring missing else branches has a very good chance of giving you false coverage reports.
