### ISSUE TITLE
Add documentation for in browser usage

### ISSUE THREAD

**Issue by asciidisco** [gotwarlost/istanbul#16]
Hi,

first of all, pretty awesome project :)
My problem is, that I´am trying to use it as a middleware to collect some coverage informations
from my client side javascript & i´am missing some kind of docs as a starting point how to integrate
everything properly.

I can generate & run instrumented code in the client, but I´am not really sure how to generate a report out of that information. Would be really cool, if one of you guys could add some information on how to do this.

Regards

**Comment by patkujawa-wf** [comment]
@pgbakker I know this is an old thread, but I'm also interested in getting coverage without the normal unit test routines (i.e. via functional tests run by selenium and/or a user). Can you point me to any resources about how you all "got it sorted"? Thanks in advance! :)

**Comment by p-bakker** [comment]
Sorry, no idea anymore how we got it 'sorted'. Must have been something silly on our part, because I forgot and never ran into it again

**Comment by johnzheng1975** [comment]
I am disappointed that no one can provide a guide:
How to do istanbul browser testing step by step?  ;-)

**Comment by moos** [comment]
Agree docs are lacking in for browser support.  I've found [this article](https://blog.engineyard.com/2015/measuring-clientside-javascript-test-coverage-with-istanbul) useful, esp. step 3 for getting coverage stats out of test-runner into a file to be consumed by `istanbul report`.

**Comment by realnikunj** [comment]
@patkujawa-wf  Were you able to do code coverage of your browser-based code with tests that run on Selenium or by user ?
I really need help in setting up the same. Thanks!

**Comment by patkujawa-wf** [comment]
I was not; priorities changed and I wasn't able to get far enough to get anything useful, unfortunately.

**Comment by realnikunj** [comment]
@patkujawa-wf I was able to conquer this one after a lot of hit and trials in various directions, so let me know if you would like to get some info on it. We can get in touch !
Our target code is written in Angular JS.

**Comment by sonu-sdz** [comment]
@patkujawa-wf Hi, do you have any blogs or documentation on the steps you followed. I'm working on something similar.

**Comment by patkujawa-wf** [comment]
I'm sorry, I don't. It was a while ago, and I never got very far.

**Comment by realnikunj** [comment]
@sonu-sdz I am putting together all the stuff in a blog soon, probably this weekend. Will share the link here, hope that helps!

**Comment by realnikunj** [comment]
Here it is - newinautomation.blogspot.com/2017/10/browser-based-js-code-coverage-using.html

Would be happy to help if anybody faces any issue(s) while implementing.

**Comment by ORESoftware** [comment]
I wrote a nice blog post about using Istanbul + Selenium + Front-end code coverage:

https://medium.com/@the1mills/front-end-javascript-test-coverage-with-istanbul-selenium-4b2be44e3e98
