### ISSUE TITLE
support multiline?

### ISSUE THREAD

**Issue by fengmk2** [gotwarlost/istanbul#170]
https://github.com/sindresorhus/multiline

``` js
var str = multiline(function(){/*
<!doctype html>
<html>
    <body>
        <h1>❤ unicorns</h1>
    </body>
</html>
*/});
```

istanbul will remove all `/* */` comments.

**Comment by fixe** [comment]
Or you can use [ES6 template strings](http://ivc.com/blog/better-sql-strings-in-io-js-nodejs-part-2/) :D
