### ISSUE TITLE
Optimization / caching.

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#176]
I run my tests with

`NODE_ENV=test istanbul cover --print detail --report cobertura ./tests/processors/index.js"`

Using `instanbul cover` adds 5s of latency to my unit tests. I think this is because of the instrumentation step. 

Currently my tests depend on 250 files of my own and another 400 from node_modules. 

Is there anything we can do to make covering faster ?

Could I implement an md5 / mtime based cache for files ?

**Comment by SystemParadox** [comment]
I would love to see this implemented. I was going to do it manually with `istanbul instrument`, but so far I haven't found a way to tell `instanbul cover` to use the pre-instrumented version of the files.

**Comment by silkentrance** [comment]
@gotwarlost This is basically just an I/O and CPU performance issue. And waiting 5s before that 250+ files are being processed is not really an issue. Please close to increase overall confidence in this *very good* tool!
