### ISSUE TITLE
Break hook out?

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#182]
I want to write a tool that does on the fly analysis of source code.

Your `hook` mechanism seems awesome to implement my analysis machine.

it would be create if it could be broken out into either `instanbul-hook` or `istanbul-core/hook` :)

I can help with this if it's preferred

**Comment by silkentrance** [comment]
@gotwarlost this is very old and most provably also a non requirement. please close to increase overall confidence in this *very good* tool!
