### ISSUE TITLE
Do not include ignored code in cobertura reports

### ISSUE THREAD

**Issue by maxklenk** [gotwarlost/istanbul#208]
The html reporter does not include code which was excluded using ```/* istanbul ignore <word> */```, but the cobertura reporter does.

It should:
> Coverage reporting however takes the skip attribute into account and artificially increments counts, when 0 and skipped to pretend that the thing in question was covered.

**Comment by TomDmitriev** [comment]
Any chances this isssue will be solved in near future? We use cobertura reports in Jenkins, and it is frustrating to see it shows the coverage lower than it actually is.

**Comment by maxklenk** [comment]
It looks like @verkholantsev is working on it: #238

**Comment by davyboyhayes** [comment]
Now that #365 has been merged... any idea when a new release will be available please?

**Comment by destroyerofbuilds** [comment]
@maxklenk and @davyboyhayes looks like this change has been in since v0.3.15

Can this issue be closed out?

**Comment by davyboyhayes** [comment]
@destroyerofbuilds - I've just rebuilt my node_modules on my build boxes, which brought in 0.3.22, and yes this has been fixed! Thanks guys!

**Comment by maxklenk** [comment]
Thank you, it works now!
