### ISSUE TITLE
Help request: No coverage information was collected

### ISSUE THREAD

**Issue by apond** [gotwarlost/istanbul#231]
I am attempting to get coverage information on my project.  I am not running a test but going through some manual scenarios.  This is the command I run:
$ istanbul cover node_server/start.js --root target/jstarget/ -v

The start.js file starts my node server.  I then use a browser to load some pages from the server that uses code in target/jstarget.  When I have run through my manual test I shutdown the server.  At that point I get this message:
No coverage information was collected, exit without writing coverage information

I feel like I am missing a step or some sort of configuration.  Could you please help me troubleshoot?

**Comment by jay4github** [comment]
You could get the coverage info through something like this (in Java):
```JavascriptExecutor js = (JavascriptExecutor) driver;
Object coverageObject = js.executeScript("return JSON.stringify(window.__coverage__);");

FileWriter file = new FileWriter("/someLocation/coverage/coverage.json")) {
file.write(coverageObject.toString());
```
Then, you can run ```istanbul report --root /someLocation/coverage/ --dir newReportLocation``` to generate the report based on that collected data.
