### ISSUE TITLE
generators not being counted as run

### ISSUE THREAD

**Issue by yawnt** [gotwarlost/istanbul#248]
i'm using co-mocha to run my tests

here's an example: https://gist.github.com/yawnt/8f3f04fcffe3e0ec597d

output:

```
┌(yawnt@ehecatl) (node 0.11.13)
╰─(/tmp/example)> npm run-script cov

> example@0.0.0 cov /tmp/example
> istanbul cover _mocha -- -u exports -R spec test-index.js


  test
    func
      ✓ should give me the correct result 


  1 passing (5ms)

=============================================================================
Writing coverage object [/tmp/example/coverage/coverage.json]
Writing coverage reports at [/tmp/example/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 60% ( 3/5 )
Branches     : 100% ( 0/0 )
Functions    : 0% ( 0/1 )
Lines        : 60% ( 3/5 )
================================================================================
```
if you look at the generated html, you'll see that the generator `func` is marked in yellow

ps: i have `node` aliased to `node --harmony`, so you might have to fix that to get the `npm run-script cov` to work

**Comment by GuillaumeCisco** [comment]
Same issue for me.
Any news about that?

**Comment by gotwarlost** [comment]
Your tests are not being run when under coverage because of the lack of `--require co-mocha` in your `cov` script.

**Comment by GuillaumeCisco** [comment]
@gotwarlost  Adding `--require co-mocha` does not change a thing...
My cover command is:
`./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --require co-mocha --compilers js:babel-register \"./src/frontend/js/**/*.spec.js\"`

**Comment by gotwarlost** [comment]
My comment was strictly based on the gist that you posted where the addition of `--require co-mocha` actually runs the tests and reports 100% coverage. Looks like your sample gist is not representative of the tests you are actually running.
