### ISSUE TITLE
how to ignore a catch statement?

### ISSUE THREAD

**Issue by jonathanong** [gotwarlost/istanbul#265]
```js
try {

} /* istanbul ignore next */ catch (err) {

}
```

**Comment by davglass** [comment]
Not sure if this is a question or a statement. Closing, please re-open if there is an issue.

**Comment by rpaterson** [comment]
I think it was a question - how do you ignore a catch statement?  The posted code doesn't work.

**Comment by rpaterson** [comment]
Got it - you ignore the code within the catch statement, not the catch statement itself. So:
```JavaScript
try {
    //...
} catch (error) {
    // istanbul ignore next
    //...
}
```

**Comment by tuhoojabotti** [comment]
@rpaterson This gets a bit tedious if I have for example a pattern to log and throw the error. I have to add a comment before both lines, instead I could say `// istanbul ignore catch` to ignore the catch altogether.

**Comment by rpaterson** [comment]
That sounds great - could you post a code example?

**Comment by tuhoojabotti** [comment]
@rpaterson Sorry I confused you with with the collaborator, there is more recent issue with more details. #361

**Comment by DomnMihai** [comment]
try {
    //...
} catch (error) /* istanbul ignore next */ {
    //...
}
