### ISSUE TITLE
Coverage output is . . . bizarre

### ISSUE THREAD

**Issue by tandrewnichols** [gotwarlost/istanbul#273]
This isn't (probably) a bug. I think I just need to be pointed in the right direction to set this up correctly. I'm trying to generate code coverage using istanbul for a suite of webdriver-based tests against an angular application. Everything seems to work as expected, but the html report is bizarre:

![screen shot 2014-11-04 at 11 25 24 am](https://cloud.githubusercontent.com/assets/2755760/4903251/396a2332-643f-11e4-86ce-aa5161e9d1f2.png)

When I dig into specific folders, the results are the same. _However_, when I open a file, it shows that most of it is _not_ covered:

![screen shot 2014-11-04 at 11 26 50 am](https://cloud.githubusercontent.com/assets/2755760/4903284/6bceebbe-643f-11e4-924a-b7f30f216474.png)

Since the tests span multiple pages, I'm assuming I need to capture `window.__coverage__` in an `afterEach`. Here's the entirety of the coverage helper (but with some comments added):

```coffee
fs = require 'fs-extra'
extend = require 'config-extend'
path = require 'path'
root = path.resolve __dirname, '../../../'
coverage = {}

class jasmineCoverageReporter
  constructor: ->
  reportRunnerResults: ->
    fs.outputFileSync root + '/reports/coverage/wd/coverage.json', JSON.stringify(coverage, null, 2)

jasmine.getEnv().addReporter(new jasmineCoverageReporter())

afterEach ->
  if process.env.WD_COV
    # "browser" is the driver instance and "eval" is a simple wrapper for "executeScript"
    cov = browser.eval "window.__coverage__"
    extend coverage, cov
```

Additionally, I'm instrumenting the code in advance and serving it in place of the regular client-side app during the test run.

Is the report just strange because all of angular's functionality happens inside a function? Is there something I'm doing wrong or can do differently to generate more accurate coverage?

Or maybe I shouldn't be extending the existing coverage with the newly collected coverage? It looks like the `istanbul report` command can handle multiple coverage objects . . . so maybe I should just write a new coverage file each time?

**Comment by petkaantonov** [comment]
You can't just `extend coverage, cov` to merge, easiest way is to push them into an array and let the reporter merge them correctly.

**Comment by tandrewnichols** [comment]
Yeah, I figured that could be an issue. But I tried your way too, and it resulted in the same messed up output. I'll try it again though, just to make sure.

**Comment by tandrewnichols** [comment]
Hmm, got an error:

```
Running "istanbul:wd" (istanbul) task

/Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/lib/collector.js:68
        Object.keys(coverage).forEach(function (key) {
               ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.Collector.add (/Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/lib/collector.js:68:16)
    at /Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/lib/command/report.js:111:27
    at Array.forEach (native)
    at /Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/lib/command/report.js:109:19
    at /Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/lib/util/file-matcher.js:35:9
    at Object.next (/Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/node_modules/fileset/lib/fileset.js:41:14)
    at Fileset.emit (events.js:95:17)
    at Fileset.next (/Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:343:12)
    at Fileset.Glob._processEmitQueue (/Users/AndrewNichols/code/anichols/manta/manta-frontend/node_modules/grunt-simple-istanbul/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:310:12)
```

The files are there:

```
AndrewNichols:manta-frontend$ ls reports/coverage/wd/coverage-
coverage-0.json   coverage-16.json  coverage-23.json  coverage-30.json  coverage-38.json  coverage-45.json  coverage-52.json  coverage-6.json   coverage-67.json  coverage-9.json
coverage-1.json   coverage-17.json  coverage-24.json  coverage-31.json  coverage-39.json  coverage-46.json  coverage-53.json  coverage-60.json  coverage-68.json  
coverage-10.json  coverage-18.json  coverage-25.json  coverage-32.json  coverage-4.json   coverage-47.json  coverage-54.json  coverage-61.json  coverage-69.json  
coverage-11.json  coverage-19.json  coverage-26.json  coverage-33.json  coverage-40.json  coverage-48.json  coverage-55.json  coverage-62.json  coverage-7.json   
coverage-12.json  coverage-2.json   coverage-27.json  coverage-34.json  coverage-41.json  coverage-49.json  coverage-56.json  coverage-63.json  coverage-70.json  
coverage-13.json  coverage-20.json  coverage-28.json  coverage-35.json  coverage-42.json  coverage-5.json   coverage-57.json  coverage-64.json  coverage-71.json  
coverage-14.json  coverage-21.json  coverage-29.json  coverage-36.json  coverage-43.json  coverage-50.json  coverage-58.json  coverage-65.json  coverage-72.json  
coverage-15.json  coverage-22.json  coverage-3.json   coverage-37.json  coverage-44.json  coverage-51.json  coverage-59.json  coverage-66.json  coverage-8.json   
```

**Comment by petkaantonov** [comment]
The passed `coverage` object is:

```js
var coverageObject =  JSON.parse(fs.readFileSync(file, 'utf8'));
collector.add(coverageObject);
```

So in some of your files the json might incorrectly be `null` or such

**Comment by tandrewnichols** [comment]
Yeah, logging at that point, one of them is null. But how do I figure out which one? Tried counting up and logging the number. It's the 53rd file, but that doesn't, apparently, correspond to coverage-53.json because that file has valid JSON.

**Comment by petkaantonov** [comment]
53rd file is 69, 70, 71, or 72 because the files are not in ascending order like that I think

**Comment by tandrewnichols** [comment]
It was 57. They're read alphabetically, so 0, 1, 11, 12, 13, etc. Any idea why one would be null?

**Comment by tandrewnichols** [comment]
Deleted that one, then the report ran fine, but the output is the same: 
![screen shot 2015-01-22 at 5 34 50 pm](https://cloud.githubusercontent.com/assets/2755760/5866185/0882071a-a25d-11e4-8365-928d8d33d3d2.png)

**Comment by tandrewnichols** [comment]
Update: I was able to solve this issue. The problem was trying to capture coverage in an afterEach, since webdriver tests sometimes change pages, which results in the `__coverage__` object being reset. I can't explain why this made the coverage report look the way it did . . . that still seems weird. But here's the solution I used to collect the coverage information whenever the page was changing:

```js
(function() {
  window.onunload = function() {
    var xhr = new XMLHttpRequest();
    xhr.open('POST', 'http://local.manta.com:8000/coverage/wd', false);
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.send(JSON.stringify({ coverageObj: window.__coverage__ }));
  };
})();
```

Then on my server, I've got this:

```js
var router = module.exports = require('express').Router();
var fs = require('fs-extra');
var path = require('path');
var root = path.resolve(__dirname, '../..');
var rnd = require('randomstring');
var bodyParser = require('body-parser');
var _ = require('lodash');

// Note this. Important because the size of the coverage object is significant.
router.use(bodyParser({limit: '50mb'}));

router.post('/wd', function(req, res) {
  if (_.isObject(req.body.coverageObj)) {
    var r = rnd.generate(5);
    fs.outputFile(root + '/reports/coverage/wd/coverage-' + r + '.json', JSON.stringify(req.body.coverageObj), function(err) {
      if (err) {
        res.status(500).send(err);
      } else {
        res.status(200).end();
      }
    });
  } else {
    res.status(500).json({ description: 'No coverage included' });
  }
});
```
