### ISSUE TITLE
All stack traces point to line 9

### ISSUE THREAD

**Issue by NiGhTTraX** [gotwarlost/istanbul#274]
## Need

``` gherkin
As a developer
I want meaningful stack traces
So that I can quickly debug.
```
## Deliverables
- [ ] Stack traces point to the original line.
#### Notes

Right now, Istanbul seems to put the entire instrumented code on line 9 so every stack trace will point to line 9 which is not very useful. The first 8 lines seem to be setup code for tracking coverage

A quick win would be to preserve line numbers in the instrumented output. Another way would be to generate source maps.

Thoughts?

**Comment by tlhunter** [comment]
:+1:

**Comment by gotwarlost** [comment]
This probably needs source maps to do it correctly.

**Comment by lo1tuma** [comment]
Same here.

Source map support would be awesome, not only to fix this bug.

**Comment by gotwarlost** [comment]
I have not looked at source maps in any depth but I recall that one of the blockers for source map support is an assumption that istanbul makes when instrumenting the code. Which is that "there is exactly one file being covered". It pulls the coverage object for the file from the global object just once and writes to it.

Having to deal with source maps breaks this assumption because the mapping might point to different files in different parts of the same source (e.g. bundling use cases).

The instrumenter needs to be made more intelligent to handle this case but at the same time the instrumented code should not take a massive performance penalty for the common use case of one source per file.

**Comment by lucastan** [comment]
is there a way to fix this?

**Comment by agladysh** [comment]
+1

**Comment by azevedo-252** [comment]
+1

**Comment by nayanbhana** [comment]
+1

**Comment by carsy** [comment]
:+1:

**Comment by jjvieira** [comment]
:+1:

**Comment by marcooliveira** [comment]
:+1:

**Comment by jladuval** [comment]
+1

**Comment by joanamelo** [comment]
:+1:

**Comment by Fdiazreal** [comment]
:+1:

**Comment by zanemcca** [comment]
+1

**Comment by luckscx** [comment]
+1

**Comment by abobwhite** [comment]
+1

**Comment by pghalliday** [comment]
+1

**Comment by seasick** [comment]
This should be labelled as _bug_ not _enhancement_ (imo :smile:)

**Comment by gotwarlost** [comment]
I hear you guys. The next version of istanbul will have some support to fix this. I'm in the middle of some surgery so this is not a small  addon to the current codebase.

**Comment by 9point6** [comment]
:+1:

**Comment by ChrisPearce** [comment]
+1

**Comment by jjmartin** [comment]
:+1:

**Comment by ryan-kimber** [comment]
+1

**Comment by msholty-fd** [comment]
+1

**Comment by andrezero** [comment]
+1

**Comment by no-chris** [comment]
+1

**Comment by robertherber** [comment]
+1

**Comment by darkmavis1980** [comment]
+1

**Comment by MitMaro** [comment]
Can we please stop with the +1s? They are pointless and cause spam to those of us who are interested in this issue.

If you want to watch this issue then please use the Subscribe button on the right. If you want just want to +1, then use the reaction that can be found near the bottom of the original post.

**Comment by darkmavis1980** [comment]
Yeah ok, but this is an issue open almost 2 years ago and it's rather important

**Comment by henrikrudstrom** [comment]
two and a half years...

**Comment by MitMaro** [comment]
You should take a look at [nyc](https://github.com/istanbuljs/nyc). It's the new Istanbul command line interface and, from what I can tell, supports sourcemaps.

**Comment by seasick** [comment]
Unfortunately it seems that nyc is waiting for istanbul to support source maps, see https://github.com/tapjs/node-tap/issues/231

**Comment by MitMaro** [comment]
The [README mentions source map support](https://github.com/istanbuljs/nyc#accurate-stack-traces-using-source-maps) and that issue is fairly old and closed. I haven't checked to make sure they are working as expected, but it would be worth a try.

**Comment by NiGhTTraX** [comment]
Closing this as I've switched to using `nyc` and it supports source maps.
