### ISSUE TITLE
es6 coverage with mocha

### ISSUE THREAD

**Issue by ouhouhsami** [gotwarlost/istanbul#284]
Hello, 

I tried the current command to have cover information for a test using a module written using es6.
I use https://github.com/domenic/mocha-traceur.
```
node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- --compilers js:mocha-traceur -u exports -R spec test/test.js
```
also with --hook-run-in-context

All tested pass, but at the end I get 'No coverage information was collected, exit without writing coverage information'

Any idea?

**Comment by gregglind** [comment]
(I confirm that this doesn't work for me either.)

**Comment by BobbyKostadinov** [comment]
I've got a similar problem - running es6 code with Generator functions and gulp-instanbul with --harmony flag fails.
Is Istanbul supporting es6 functions ? 

(Tests pass, coverage fails)

Apologies for if I am stealing the issue, but it would seem it can be related

**Comment by gotwarlost** [comment]
There is a branch of istanbul for `harmony` support and I believe someone has created a package for it. This is needed because `esprima` mainline does not (or, did not at that time) support es6.

https://www.npmjs.com/package/istanbul-harmony

**Comment by BobbyKostadinov** [comment]
I've tried using the harmony branch and that solved my problem! Thanks for pointing it out

**Comment by davglass** [comment]
Closing this since the harmony branch is being developed on.

**Comment by ami44** [comment]
see https://github.com/gotwarlost/istanbul/blob/master/CHANGELOG.md
since v0.3.9 : 

- Merge harmony branch and start adding ES6 features to istanbul

**Comment by gotwarlost** [comment]
Hi guys, the harmony branch should be treated as obsolete with the latest Istanbul release. The mainline release now has all the features that the harmony branch has. Let me know is thus is not the case.

**Comment by dylanfoster** [comment]
I'm still getting "No coverage information was collected, exit without writing coverage information" in an es6/babel project.

Using 0.3.17 with this command:

`istanbul cover node_modules/.bin/mocha -- --compilers js:babel/register`

**Comment by gotwarlost** [comment]
Try `_mocha` instead of `mocha` which forks and doesn't allow istanbul to instrument the subprocess code as a result.

**Comment by dylanfoster** [comment]
:+1:

**Comment by halt-hammerzeit** [comment]
Hello guys.
I'm using it like this:

```
    "test": "mocha --compilers js:babel/register --colors --bail --reporter spec test/",
    "test-cov": "istanbul cover node_modules/mocha/bin/_mocha -- --compilers js:babel/register --colors --reporter dot test/",
    "test-travis": "istanbul cover node_modules/mocha/bin/_mocha --report lcovonly -- --compilers js:babel/register --colors --reporter spec test/",
```

And travis.yaml
```
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
```

However, on the COVERALLS website the lines highlighting seems messed up - it seems to highlight the wrong lines.
Do you have any ideas what might be wrong?
I guess istanbul highlights the transpiled code, but can it highlight pure ES6?

Also, in your examples it uses babel-register which pollutes the scope with polyfills.
Can it be used with babel-require?
Because when you're writing something like `array.includes` the tests pass, but after some time you find out that your npm module actually doesn't work for your users.

**Comment by halt-hammerzeit** [comment]
By the way, while browsing babel sources I accidentally saw some `register-without-polyfill.js` and turns out that it eliminates the `Array.prototype.includes is undefined` surprises in the browser (after all the tests passed).

```
  "scripts": {
    "test": "mocha --compilers js:babel/register-without-polyfill --colors --bail --reporter spec test/",
```

**Comment by JediMindtrick** [comment]
I'm on istanbul 0.3.19, with babel 5.1.10 and mocha 2.2.4.  None of the commands above (or any other I've tried) are producing any kind of code-coverage for me.  I always get the message "No coverage information was collected, exit without writing coverage information."  I'm not sure where the best place is to ask, or who to ask...but any help is appreciated.

**Comment by ColCh** [comment]
@JediMindtrick 

Rename your **JSX** files extension to **JS**

And launch coverage with this comand:
```
babel-node node_modules/isparta/bin/isparta cover node_modules/mocha/bin/_mocha --  
```

Hope this helps.

Also: [istanbul/issues/405#issuecomment-138308669](https://github.com/gotwarlost/istanbul/issues/405#issuecomment-138308669)

**Comment by dobryanskyy** [comment]
For me - this did not help. But updating to istanbul@1.0.0-alpha.2 did.

**Comment by udnisap** [comment]
upgrading to `istanbul@1.0.0-alpha.2` indeed fixed it.

**Comment by cpselvis** [comment]
For ES6 && Mocha project，my script commands are listed below:
``` bash
  "scripts": {
    "compile": "babel --presets es2015,stage-0 -d lib/ src/",
    "test": "npm run compile && mocha --compilers js:babel-core/register",
    "cover": "istanbul cover node_modules/mocha/bin/_mocha -- --compilers js:babel-core/register --colors --reporter dot test/"
  }
```
