### ISSUE TITLE
Anonymous functions used in javascript objects are ignored by Istanbul

### ISSUE THREAD

**Issue by cbgx74** [gotwarlost/istanbul#289]
As the issue https://github.com/gotwarlost/istanbul/issues/131 is closed, I opened this one.

The reason of #131 was some issue with require.js. But I cannot find a reason of the issue in my code/configuration

My package.json contains:
"matchdep": "~0.3.0",
    "grunt": "~0.4.5",
    "grunt-contrib-connect": "~0.9.0",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-shell": "~1.1.1",
    "grunt-karma": "~0.9.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-contrib-concat": "~0.5.0",
    "grunt-open": "~0.2.3",
    "bower": "~1.3.12",
    "karma-script-launcher": "~0.1.0",
    "karma-firefox-launcher": "~0.1.3",
    "karma-chrome-launcher": "~0.1.7",
    "karma-html2js-preprocessor": "~0.1.0",
    "karma-jasmine": "~0.1.5",
    "karma-requirejs": "~0.2.2",
    "karma-coffee-preprocessor": "~0.2.1",
    "karma-phantomjs-launcher": "~0.1.4",
    "karma-coverage": "~0.2.7",
    "karma": "~0.12.28",
    "protractor": "~1.5.0",
    "grunt-protractor-runner": "~1.1.4",
    "grunt-shell-spawn": "~0.3.0",
    "jshint-stylish": "~1.0.0",
    "jasmine-reporters": "~1.0.1",
    "request": "~2.51.0",
    "bdd-using": "~0.1.0",
    "karma-bdd-using": "~0.1.0",
    "jasmine-spec-reporter": "~1.1.0",
    "karma-junit-reporter": "~0.2.2",
    "karma-jasmine-matchers": "~0.1.3",
    "jasmine-custom-message": "~0.7.2",
    "jasmine-where": "0.0.12",
    "jshint-jenkins-checkstyle-reporter": "~0.1.2",
    "datejs": "~1.0.0-rc3",
    "jasmine-core": "~2.1.3"

Searching on SO I found http://stackoverflow.com/questions/22417531/event-callbacks-code-coverage question, but it still unanswered.

**Comment by davglass** [comment]
There isn't really a lot of information in this issue, I'm closing this. If you really have a problem please open a new issue with an example/repro case that I can see and help with.
