### ISSUE TITLE
Treat assert() as a branch

### ISSUE THREAD

**Issue by dapetcu21** [gotwarlost/istanbul#290]
Right now, `assert()`s don't matter in coverage (they're always considered covered), which makes them easy to skip when writing tests. Is there any way to change that behaviour?

**Comment by danmartinez101** [comment]
You could use an if statement instead of an assert which would make this show up as a branch.

**Comment by dapetcu21** [comment]
True, but that looks considerably uglier (3 lines instead of 1), especially in a block of aprox. 10 consecutive asserts. I'm just suggesting that assert could be a frequent enough use case to warrant special behaviour.

**Comment by gotwarlost** [comment]
Not doing this. In the general case, there is no way for the instrumenter to know what the function being executed actually is unless it does a scope analysis and puts in all sorts of assumptions about how things work in `node`
