### ISSUE TITLE
Store coverage reports in a database

### ISSUE THREAD

**Issue by ilanbiala** [gotwarlost/istanbul#291]
For those of us who aren't using a code coverage service like coveralls (expensive....), it would be nice to still have the coverage tracked in our own database. That way it won't have to go through Git constantly.

**Comment by gotwarlost** [comment]
I guess you could implement your own based on istanbul's numbers? How is this the problem of the code coverage tool?

**Comment by ilanbiala** [comment]
Not a problem, just a different way of doing it..that for most people probably makes sense.
