### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by jwalton** [gotwarlost/istanbul#295]
Hi!  I'm the author of [coffee-coverage](https://github.com/benbria/coffee-coverage).  I've had some interest in getting coffee-coverage and istanbul working together, and was wondering if you had some input on what the best way to do such a thing would be?

Coffee-coverage was written to have output that's compatible with [jscoverage](http://siliconforks.com/jscoverage/), so it doesn't do any branch or function coverage (because jscoverage doesn't) but these features would be pretty easy to add (@silkentrance is [working on this right now](https://github.com/benbria/coffee-coverage/pull/34) in fact.)

What's the easiest way to get data from coffee-coverage into instanbul, though?

**Comment by silkentrance** [comment]
Never mind, just found this link which contains the information I need:

http://gotwarlost.github.io/istanbul/public/coverage/coverage.json

**Comment by soliury** [comment]
+1

**Comment by jwalton** [comment]
Here's my attempt at reverse engineering the coverage.json object:

# JSON Report Format

Top level is a hash where keys are file names, and values are coverage data for that file
(the result of `json.stringify(collector.fileCoverageFor(filename))`)  Each coverage data consists of:

* `path` - The path to the file.
* `s` - Hash of statement counts, where keys as statement IDs.
* `b` - Hash of branch counts, where keys are branch IDs and values are arrays of counts.
        For an if statement, the value would have two counts; one for the if, and one for the else.
        Switch statements would have an array of values for each case.
* `f` - Hash of function counts, where keys are function IDs.
* `fnMap` - Hash of functions where keys are function IDs, and values are `{name, line, loc}`,
   where `name` is the name of the function, `line` is the line the function is declared on,
   and `loc` is the `Location` of the function declaration (just the declaration, not the entire
   function body.)
* `statementMap` - Hash where keys are statement IDs, and values are `Location` objects for each
  statement.
* `branchMap` - Hash where keys are branch IDs, and values are `{line, type, locations}` objects.
  `line` is the line the branch starts on.  `type` is the type of the branch (e.g. "if", "switch").
  `locations` is an array of `Location` objects, one for each possible outcome of the branch.
  Note for an `if` statement where there is no `else` clause, there will still be two `locations`
  generated.  Instanbul does *not* generate coverage for the `default` case of a switch statement
  if `default` is not explicitly present in the source code.

  `locations` for an if statement are always 0-length and located at the start of the `if` (even
  the location for the "else").  For a `switch` statement, `locations` start at the start of the
  `case` statement and go to the end of the line before the next case statement (note Instanbul
  does nothing clever here if a `case` is missing a `break`.)

## Location Objects

Location objects are a `{start: {line, column}, end: {line, column}}` object that describes the
start and end of a piece of code.  Note that `line` is 1-based, but `column` is 0-based.

**Comment by jwalton** [comment]
Ok, I've hacked together a solution to this.

**Comment by gotwarlost** [comment]
That description is perfect by the way. Sorry for not responding - my day job is really keeping me busy

**Comment by jwalton** [comment]
No worries.  I'm terrible at responding to issues on my projects, too.
There's been an open issue asking for Istanbul support on coffee-coverage
for over a year.  :P
