### ISSUE TITLE
No coverage information was collected, exit without writing coverage information

### ISSUE THREAD

**Issue by dgofman-equinix** [gotwarlost/istanbul#297]
I have simple MS DOS script

@echo off

SET ISTANBUL=node_modules\.bin\istanbul
SET UMOCHA=node_modules\.bin\_mocha

cmd /c %ISTANBUL% cover %UMOCHA% -- -R spec

By running this script I got errors

basedir=`dirname "$0"`
        ^
No coverage information was collected, exit without writing coverage information
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (C:\project\node_modules\istanbul\lib\hook.js:102:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (C:\project\node_modules\istanbul\lib\command\common\run-with-cover.js:116:16)

    at C:\project\node_modules\istanbul\lib\command\common\run-with-cover.js:239:17
    at C:\project\node_modules\istanbul\lib\util\file-matcher.js:68:16
    at C:\project\node_modules\istanbul\node_modules\async\lib\async.js:254:17

**Comment by gotwarlost** [comment]
Bin file names don't work on windows. You need to find the .js file that mocha runs and use that.

**Comment by dgofman-equinix** [comment]
'Bin file names don't work on windows.' ....

Please can you give me some workaround how to execute from DOS prompt

**Comment by popomore** [comment]
@dgofman-equinix specify the file where it really is, not the symbol link.

`node_modules/mocha/bin/_mocha`

**Comment by dgofman-equinix** [comment]
Too late I found this workaround long time ago. But anyway thanks and by the way in latest mocha you don't need _mocha file anymore
