### ISSUE TITLE
Is node_modules directory automatically excluded from instrumentation?

### ISSUE THREAD

**Issue by bleurose** [gotwarlost/istanbul#299]
I am not very skilled on the use of github issues and the protocol of what is an "issue" or not but I can't find anyplace else to ask this question so I am trying here.  

My directory structure (not written by me, I am just testing it, I am not a js or node.js developer personally) is:

* topdir
  * cmd.js
  * subdir
    * work.js
  * node_modules
    * browserify
      * [several .js files]
    * watchify
      * [several .js files]

When I run instrument like this (from the directory above topdir):

  istanbul instrument -o topdir-i topdir

I get an output director topdir-i with cmd.js and subdir/work.js instrumented.  I assumed I wanted to NOT instrument node_modules subdirectories but I didn't add a directory exclusion for it.  

However, I never seem to get node_modules instrumented (whether I say exclude it or not).  

Is node_modules directory being automatically excluded for some reason?

Thanks!

Jon Rosen (bleurose)

**Comment by gotwarlost** [comment]
use `--no-default-excludes` 

```
 --[no-]default-excludes
              apply default excludes [ **/node_modules/**, **/test/**,
              **/tests/** ], defaults to true
```

**Comment by bleurose** [comment]
I think that is the answer I was looking for.  It would be nice if the default excludes were listed in the help that is returned from "istanbul help config".  I may go fix it and propose a pull for that.  

Thanks!

Jon

**Comment by bleurose** [comment]
Thanks that was what I was looking for!


   	-------Original Message-------

**Comment by davglass** [comment]
It should be noted that the quote from above was in the output of `istanbul help cover`.

**Comment by micophilip** [comment]
@gotwarlost Can someone help with the inverted scenario? I'm trying to only include specific folders in `node_modules` otherwise my exclude list would be pretty big, is this supported?.. Would I be able to do something like`!**/node_modules/my-package` where it would only include `my-package` but nothing else from `node_modules`?
