### ISSUE TITLE
yet another "no coverage information was collected" example

### ISSUE THREAD

**Issue by gregglind** [gotwarlost/istanbul#300]
https://github.com/gregglind/yet-another-istanbul-mocha-no-coverage

Clearly, I am doing something wrong :)  Insights about what are welcome!

(Wrong versions of libs?)

**Comment by davglass** [comment]
Sorry for the delay, the reason it's not covering `./test/lib.js` is because it's in the `./test` directory. Istanbul automatically ignores some directories by default and the tests are part of it.
