### ISSUE TITLE
Probably a dumb question but I am not getting output from "instrument"ed code at all

### ISSUE THREAD

**Issue by bleurose** [gotwarlost/istanbul#301]
I read through several other issues (including closed ones) to see if I was missing something obvious and one of the issues did say that coverage for pre-instrumented code goes to "global.\_coverage\_ in node" but when I search the directory structure, I do not find any "global.\_coverage\_" directory anywhere.  

Here is what I am doing:

1. I have several directories with node .js files (for the moment, we will just say there are two directories called "rest" and "cli" and each has a cmd.js file.)  I want to run an integration test suite which starts both our cli listener/server and our rest listener/server.  The tests call our cli interface which in turn calls the rest interface.  The goal is to see how much coverage of our system our integration tests are providing (we already have unit test coverage but we are more interested in coverage between all of our modules which are highly interrlated).  

2. I execute the following command on each directory from the upper src directory:

    istanbul instrument --output rest-covered --embed-source --no-compact --preserve-comments rest
    istanbul instrument --output cli-covered --embed-source --no-compact --preserve-comments cli

3. I now switch the xxxx-covered and xxxx directories for each, so that the covered code ends up under the main directory name (there are other parts of our build process that depend on these names being the ones it knows about).  

4. I execute the two servers with no special options.

5. I shut down the servers with their appropriate "shutdown" commands (which shuts them down cleanly).  

At this point, nothing is written to the output streams for either server and I can't find any coverage folders (or \_coverage\_ folders, etc.)  

BTW, when I execute EITHER of the two servers manually and independently with istanbul, i.e.:

   istanbul cover rest/cmd.js ...

and shut that server down properly, it gets its own "coverage" folder in that directory and it all works.  However, I can't execute things that way in our build system (at least I don't know how to change that easily).  Plus, my whole purpose is to get integrated coverage of all of the .js files we have (we actually have over a dozen different "packages" that use javascript that I need to instrument simultaneously to really make this work fully, but I've been working on a subset just to make sure I can do it at all.

Thanks for any help!  (I greatly appreciated your fast response to my questions.  Sorry for my ignorance, but I can't find any other documentation on how to use the instrument option.

Jon Rosen

**Comment by gotwarlost** [comment]
`istanbul cover` hooks into `process.exit` to dump the coverage on process exit. The instrumented files themselves do not do this.

Have you tried [istanbul-middleware](https://github.com/gotwarlost/istanbul-middleware) ? This is _probably_ what you need.

**Comment by gotwarlost** [comment]
https://github.com/gotwarlost/istanbul/blob/master/lib/command/common/run-with-cover.js#L197 shows you what happens during `istanbul cover` on process exit.

**Comment by bleurose** [comment]
That was VERY helpful.  And just to verify, "istanbul cover" ONLY 'covers' the code in the single .js file that is run via node?  Is it true that any other .js files that are "required" by the executed .js file do NOT get covered?  What if the other .js files that are "required" are pre-instrumented (with istanbul instrument)?  I.e., if "cmd.js" requires "test.js" and test.js has been instrumented previously, will running cmd.js with "istanbul cover" get coverage for both cmd.js AND test.js or for cmd.js only?  

Again I apologize if this is basic stuff, I am a python expert but I am barely functional in js and node.js (although I like some of the capabilities I am seeing in .js and will probably look at this more closely when I have time).  But it does make it difficult for me to prowl through the source code and figure out what is happening (although pointing me to something like you did above really does make it a lot easier for me so thanks again!)

Jon

**Comment by gotwarlost** [comment]
No, `istanbul cover` hooks `require` as well so everything that is required is automatically covered.

**Comment by bleurose** [comment]
Awesome!

Thanks again, Jon

**Comment by Mickael-van-der-Beek** [comment]
This issue can probably be closed I think ?
