### ISSUE TITLE
Server wont start with "istanbul cover server.js" - but other works fine!

### ISSUE THREAD

**Issue by MattCollins84** [gotwarlost/istanbul#302]
I have 2 projects, both are very similar in terms of their architecture etc...

For project 1, if I do: istanbul cover server.js
The server starts up after a few seconds of high CPU usage

For project 2, if I do: istanbul cover server.js
My CPU stalls at near 100% for a long time (20 minutes before I gave up)

Both projects are working fine independently, and project 1 is much bigger and verbose than project 2 so I'm not sure where to look. There is no output at all after running cover for project 2.

Are there any obvious things that I can look for?
Matt

**Comment by gotwarlost** [comment]
This is usually because the istanbul file matcher loads up all files under the directory tree and with a large number of files, it can choke...
