### ISSUE TITLE
Code coverage of JS on a HTML web page

### ISSUE THREAD

**Issue by shubhendra** [gotwarlost/istanbul#307]
Hi Guys,

I have a quick question. Can I use Istanbul to see the code-coverage of Javascript on a webpage i.e. all the JS that is executed on a page, not the ones triggered by writing unit tests.

Thanks :)

**Comment by davglass** [comment]
If you are serving it locally you can use the [`istanbul-middleware`](https://github.com/gotwarlost/istanbul-middleware) node module to instrument the files on the fly as they are being served.
