### ISSUE TITLE
Feature Request: ability to ignore helper functions added by transpilers

### ISSUE THREAD

**Issue by goatslacker** [gotwarlost/istanbul#308]
6to5 adds quite a few helper functions to the top of the file, it would be cool to have these ignored by istanbul.

**Comment by plestik** [comment]
FYI, this is configurable in babel: 
https://github.com/babel/babel/issues/777

Here's what it looks like for karma:
```javascript
babelPreprocessor: {
			options: {
				auxiliaryComment: 'istanbul ignore next'
			}
		}
```

**Comment by destroyerofbuilds** [comment]
@goatslacker is the `auxiliaryComment` option sufficient for your needs?

**Comment by goatslacker** [comment]
I've been actually transpiling it using the babel external files and then requiring a test helper that auto includes them
