### ISSUE TITLE
Excluding directory from coverage

### ISSUE THREAD

**Issue by emascarinas** [gotwarlost/istanbul#312]
Hi there, I'm using ionic for our app and I can't seem to exclude the www/libs/ folder for the coverage. Its covering js files inside the "lib" folder. The directory structure of ionic is www/libs and www/js where "js" is the main src js files but needs the lib folder to run the app.

I only wanted to get coverage on the www/js folder, is it possible? I tried using env: coverage APP_DIR..: '../intrumented/www/js/' but its not working.

My current Gruntfile.js
*********************************
```javascript
copy: {
            'instrument': {
                files: [{
                        src: ['www/**/*', '!www/**/*.js'],
                        dest: 'instrumented/'
                    }]
            }
        },
        instrument: {
            files: 'www/**/*.js',
            options: {
                basePath: "instrumented"
            }
        },
```
********************

Thanks in advance!

**Comment by gotwarlost** [comment]
I have no idea on what the grunt tasks do. Please raise this issue with whoever has written the grunt task. istanbul gives you options to include and exclude directories.

**Comment by emascarinas** [comment]
Just adding the solution I found. Thanks

http://chawi3.com/2015/02/16/grunt-protractor-coverage-exclude-files-or-directory-angularjs/
