### ISSUE TITLE
Trouble CSS with Unix path on Windows script

### ISSUE THREAD

**Issue by shenron** [gotwarlost/istanbul#315]
I use karma-coverage for start Istanbul with src path like this :
 'src/main/test/**/*.js'

All HTML files generated have wrong CSS path. They try to load parent CSS with '../'. But only root folder has CSS file ...
I read the code, I think I found something wrong:

For set URL CSS dependencies in HTML, /lib/report/html.js use path module :
```javascript
    path = require('path'),
    SEP = path.sep || '/',
```
So, if you start istanbul with Unix path on Windows, all CSS are broken. Script split on bad SEP. 

```javascript
for (i = 0; i < num; i += 1) {
                    separated = node.relativeName.split(SEP);
                    levels = separated.length - 1;
                    for (j = 0; j < levels; j += 1) {
                        href += '../';
                    }
                    node = node.parent;
 }
```

To fix quickly, I rewrite sep before starting istanbul:
```javascript
 require('path').sep = '/';
```

**Comment by erikdonohoo** [comment]
:+1:  This is a problem for me too.

**Comment by gotwarlost** [comment]
So what do you want istanbul to do? You want an option to force Unix style paths irrespective of target environment?

**Comment by shenron** [comment]
I think, an option to choose path style is good solution.

**Comment by erikdonohoo** [comment]
I agree.  Much like the [grunt-sftp](https://github.com/thrashr888/grunt-sftp-deploy) package has a `serverSep` option to define what style of separators you want.  You could add a similar option.

**Comment by einarq** [comment]
Problem for us too. Only started happening recently though, after the last npm update. Worked on 0.3.5, started failing on 0.3.6. Any chance of just reverting to the old behavior?

**Comment by MarkusPint** [comment]
+1
