### ISSUE TITLE
`istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly` somehow only generates `coverage.json`

### ISSUE THREAD

**Issue by stevemao** [gotwarlost/istanbul#318]
I just started using `istanbul` in my modules and `istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly` somehow only generates `coverage.json`, hence it fails to push results to coveralls

I'm **new** to istanbul so please let me know if I've done anything wrong.

I can provide more details if needed but you can check this out yourselves.

https://travis-ci.org/stevemao/git-raw-commits/jobs/52381947

**Comment by davglass** [comment]
Your builds seem to be posting now, did you figure out the issue?

**Comment by stevemao** [comment]
No, I removed `--report lcovonly`. If I didn't remove it it would still fail. I think you should just look at the build in the link https://travis-ci.org/stevemao/git-raw-commits/jobs/52381947

**Comment by davglass** [comment]
Thanks for the update, I've tracked down the bug. The `lcov.info` file is being generated, but it's being placed in the `./tmp` directory that your tests are writing to. Your test file is executing a `shell.cd('tmp')` and when the report is writing out it's using `process.cwd()` (which it shouldn't).

**Comment by stevemao** [comment]
Oh that make sense :smile:
