### ISSUE TITLE
add junit xml report option

### ISSUE THREAD

**Issue by JaKXz** [gotwarlost/istanbul#326]
It would be awesome to have an `istanbul report junit` task that produces JUnit XML so that tools like CircleCI can easily infer test results :smile: 

Love using istanbul so far! :+1:

**Comment by gotwarlost** [comment]
istanbul is a coverage tool and not a testing tool. It has no idea what happened to your tests. You'll need to produce test reports yourself.

**Comment by JaKXz** [comment]
I meant to say: can easily infer test *coverage* results.

**Comment by Pyrolistical** [comment]
@gotwarlost You didn't understand OP's request.  He wants a failing junit report when there is missing coverage.

eslint is not a unit testing tool, yet it can be configured to produce a junit result xml for each linting error.

istanbul can do the same thing and for every line that missed coverage, generate a failing junit test result.

if you do this, then we can get nice reporting in circle ci like:
<img width="1073" alt="screen shot 2016-06-21 at 4 15 51 pm" src="https://cloud.githubusercontent.com/assets/463642/16249543/75080fba-37cb-11e6-82b2-1775d564fc40.png">
