### ISSUE TITLE
Weird or incoherent coverage

### ISSUE THREAD

**Issue by yanickrochon** [gotwarlost/istanbul#337]
I just added istanbul to [a project](https://github.com/yanickrochon/koa-rbac) and tested it to get this result 

```
=============================== Coverage summary ===============================
Statements   : 95.68% ( 133/139 )
Branches     : 89.09% ( 98/110 )
Functions    : 90.91% ( 20/22 )
Lines        : 95.68% ( 133/139 )
================================================================================
====================
TOTAL COVERAGE: 8%
```

The total coverage is quite odd. And when I open the generated HTML file, nothing has been covered. The command generate coverage is 

```
node --harmony node_modules/istanbul-harmony/lib/cli.js cover node_modules/mocha/bin/_mocha
```

There are 7 tests and [all are passing](https://travis-ci.org/yanickrochon/koa-rbac).

Oddly, coveralls.io reports a [more correct result](https://coveralls.io/r/yanickrochon/koa-rbac)...

**Comment by gotwarlost** [comment]
The `TOTAL COVERAGE` message is **not** emitted by istanbul. Please bug whoever is emitting it and figure out why they are not generating the HTML reports right.

**Comment by yanickrochon** [comment]
Right! It was `semicov`. I removed the dependency and now everything is fine. Cheers!
