### ISSUE TITLE
HTML Reporter throwing an error [TypeError: Cannot set property 'covered' of undefined]

### ISSUE THREAD

**Issue by jsnsimpson** [gotwarlost/istanbul#341]
I'm running my unit tests with browserify and karma-coverage. An error gets thrown: 

[TypeError: Cannot set property 'covered' of undefined]

If I add in: 

if(structuredText[lineNumber]) {
  structuredText[lineNumber].covered = count > 0 ? 'yes' : 'no';
}

everything works as expected.

Obviously this doesn't eliminate the root cause of the issue (why is there an undefined lineNumber in the structuredText?) But its got me running for now.

**Comment by cvbuelow** [comment]
I'm seeing the same

**Comment by jeffkole** [comment]
Is it possible you are running into the same condition as in #94?

**Comment by fabiancook** [comment]
Might not be the same thing, but I found I got this error if I had an empty source file.

**Comment by davglass** [comment]
Fixed in #331
