### ISSUE TITLE
Left-align file list

### ISSUE THREAD

**Issue by Eugeny** [gotwarlost/istanbul#348]
When using a "proper" nested filesystem layout, the right-aligned **file** column lowers readability of the paths. 

Before:
![selection_084](https://cloud.githubusercontent.com/assets/161476/7202980/70ebba2e-e517-11e4-8d91-9909679ec330.png)

After:
![selection_085](https://cloud.githubusercontent.com/assets/161476/7202981/742fa894-e517-11e4-87cd-3ae041cb94c6.png)

**Comment by davglass** [comment]
Fixed in #345
