### ISSUE TITLE
Missing "else" changes branch percentage

### ISSUE THREAD

**Issue by mbielski** [gotwarlost/istanbul#35]
When a script contains an "if" without an "else" the file is flagged for not having covered the "else" that isn't there. This changes the total coverage of the branches incorrectly when the contents of the "if" are fully covered. The lone "if" should be detected correctly.

**Comment by tomasdev** [comment]
how do you test

```for (var property in defaultValues) {
          Eif (defaultValues.hasOwnProperty(property)) {
            $window.s[property] = defaultValues[property];
          }
        }``` ?

**Comment by tomasdev** [comment]
```
var parent = { key: 'value' };
var child = Object.create(parent);
child.key2 = 'value2';
// ...
expect($window.s.key).toBeUndefined();
expect($window.s.key2).toBe('value2');
```

**Comment by gotwarlost** [comment]
@tomasdev  - these are the hard-to-test cases where you can use `/* istanbul ignore else */` to signal that the `else` path is hard to test or untestable.

**Comment by jt3k** [comment]
why istanbul show warning only on first IF (on line 35) but ignore second IF (on line 42)
!(https://i.imgur.com/Hm26ar6.png)

result in htmlview
!(https://i.imgur.com/rZUHQdr.png)

**Comment by robsonbittencourt** [comment]
@jt3k Probably you have not tested the 4 possibilities of your if.

**Comment by jt3k** [comment]
@robsonbittencourt why did you write this text? can't you see my question?

**Comment by robsonbittencourt** [comment]
Yes it can. I replied because I think the warning refers to you don't have covered the four possibilities of first if. Already the second if must have had his two possibilities covered.

**Comment by iturgeon** [comment]
If I can contribute to this at all, I think the error could use a more explicit description.

We just started using istanbul and didn't understand the output. Initially the developer assumed the test wasn't getting into the `if` block (because it indicated it wasn't covered).  That led to some crazy misunderstandings of how istanbul was evaluating code. 

After reading the error completely, the developer realized it was complaining about an `else` not being run, but when we looked at the source, there was no else statement at all.  The developer was pretty confused, a lot of random things seemed to be occurring.

At this point, the first assumption was that for some reason istanbul required `if` statements to have `else` statements, which seemed crazy.  Eventually we uncovered this github issue and figured out what is really happening.

After seeing this happen, it seems reasonable that it would happen to others. I believe making the user aware that this coverage test requires `if` statements to eval as `true` and `false` will help save some headaches.

**Comment by lifeich1** [comment]
```javascript
var isEmptys = function() {
    var obj = this;
    for (key in obj) {
        E if (typeof(obj[key]) !== 'function' && obj[key]) {
            return false;
        }
    }
    return true;
}
```

The disturbing "else path not taken" occurs when I test the code in all cases:
```javascript
            (isEmptys.call({})).should.be.true();
            (isEmptys.call({9:1})).should.be.false()
```

**THAT MAKES ME MAD!!!**

**Comment by jt3k** [comment]
@lifeich1 I agree with you.
That is idiotism :(

**Comment by lifeich1** [comment]
I found I made a mistake. There is an another testcase:
```javascript
            (isEmptys.call({1:function() {}})).should.be.true();
```
I am sorry for ignoring that case.

**Comment by andreyluiz** [comment]
Just contributing with a practical example of how to get rid of this problem. I have the following:

```js
async updateTravelInfo(newLocation) {
  if (!isEqual(newLocation, this.props.location)) {
    // update location accordingly
  }
  // Nothing to do
}
```

In other words, the update location stuff only needs to be called if the location changes. To test this, I have the following:

```js
test("fetches travel info when location changes", () => {
  const travelTime = jest.spyOn(baseProps.locationsService, "getTravelInfo");

  travelTime.mockResolvedValue({ time: "100 anos", from: "Madrid" });

  const wrapper = shallowWithContext(
    <Home {...baseProps} />,
  );

  wrapper.setProps({
    location: {
      location: {
        latitude: 12,
        longitude: 21,
      },
    },
  });

  // FUNCTION called the first time (if taken)
  expect(travelTime)
    .toHaveBeenCalledWith({
      lat: 12,
      lng: 21,
    });

  // Set the same props as before
  wrapper.setProps({
    location: {
      location: {
        latitude: 12,
        longitude: 21,
      },
    },
  });

  // The function should have been called just once!
  // The error disappeared from coverage report.
  expect(travelTime)
    .toHaveBeenCalledTimes(1);
});
```

With this I have no uncovered branches.

**Comment by justinpincar** [comment]
So I understand your philosophy _now that I've read through this thread_, but you have to admit this is hella confusing if you're just looking at the reports. 100% of statements, 100% of functions, and 100% of lines covered, with line 12 uncovered. Mmmk.

```

File                 |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------------|----------|----------|----------|----------|-------------------|
  logger.js          |      100 |       75 |      100 |      100 |                12 |
```

Instanbul is a great tool; it would be nice if it supported more use cases.

**Comment by vkiperman** [comment]
> I disagree. This is not a "feature."
> 
> In order to "test" the "empty else block that notionally exists" I actually have to add something to the script that does nothing. That doesn't lint well, and it is just plain poor programming practice. Can you at least provide a configuration option to turn this off?

It simply means you have to provide a spec that tests the else case. There's no need to add useless code.

**Comment by vkiperman** [comment]
> Ok, now let me give you an example of why istanbul is not working correctly. Let's say that we want to display temperatures in celsius if and only if our visitor is from a non-US country, and we have a function that does the checking for us, like so:
> 
> var foo, ab;
> 
> ab = "32 Degrees";
> 
> foo = visitorIsNotUSBased();
> 
> if (foo) {
> ab = convertFarenheightToCelsius(ab);
> }
> 
> $('#waterfreezes').val(ab);
> 
> In the example above there is no else because we don't want to do anything to ab if foo is not true. Running this code through istanbul with the appropriate tests, it will nag at me for an else that not only does not exist but does not have to or need to exist. Why is that correct?

in this example, ab can have one of two possible values. But, you are only testing it for one of the values. Technically, your coverage is incomplete.
What happens when you call expect($.val).toHaveBeenCalledWith(?), you should cover all the ways the val can be called.

**Comment by vkiperman** [comment]
My question is, if there is nothing at all after the `if` statement, where the `if` statement is the only thing inside a `function`.
```
public set initialData(value: string) {
      if (value) {
        this.form.get('selection').setValue(value);
      }
   }
```
What's the advantage of mocking the `else` case and having that coverage?

**Comment by kammanageswararao** [comment]
HI Can you please assist the below test cases in angular?

Here i have written one test case 

it('productSelection', async(() => {
    spyOn(component, 'productSelection');
    const btn = fixture.debugElement.query(By.css('.BPNormal'));
    btn.triggerEventHandler('click', 'productSelection');
    fixture.whenStable().then(() => {
      expect(component.productSelection).toHaveBeenCalled();
    });
  }));

still in code coverage showing  conditional 50 % (1/2).
Could you please please provide me the expecting test cases example.

Thanks in advance.

**Comment by joelgetaction** [comment]
I just encountered this.  I still don't understand why this is considered a "feature".  Take for example the following:
```
if (typeof x !== "number") {
  ...
} else if (x > 2) {
  ...
} else if (x <= 2) {
 ...
}
```
Why mark that as `else path not taken` - it is logically impossible for the else path to be taken, provably so.  Why should I get less than 100% coverage here when under no system of logic could the else path ever be taken let alone need to be coded let alone need to be tested?

I don't understand ... :-(

**Comment by vkiperman** [comment]
The last `else if` in the above code can be `else`. That should solve the problem.

Your code could also be rewritten in this way:
```
if (typeof x !== "number") {
    ...
    return
} else if (x > 2) {
    ...
    return
}
...
```
This way all the cases can be covered. It's my opinion that the `else` path coverage rules are designed to force us to write `if-else` statements this way. I'm still trying to understand the coverage rules.

**Comment by mgartner** [comment]
@joelgetaction I think there is actually an implicit else that is possible, even though Istanbul isn't "smart" enough to know whether or not that is the case (I think).

```node
$ node
> x = NaN
NaN
> typeof x
'number'
> x > 2
false
> x <= 2
false
```

**Comment by hasezoey** [comment]
I dont really understand why this is a feature and has no config options, because of the following [example](https://github.com/hasezoey/typegoose/blob/aa86c978edc07c1dc166b3c55a8b4b47e8bec841/src/typegoose.ts#L162-L173)
(context: this is inside an function that assembles an mongoose Schema)
```ts
// interface BaseVirtual {
//   options?: {
//     [key: string]: any;
//     overwrite: boolean;
//   };
//   get?(): any;
//   set?(toSet: any): any;
// }
// getterSetters is of type Map<string, BaseVirtual>
// sch is of type mongoose.Schema<any>
for (const [key, virtual] of getterSetters) {
  if (virtual.options && virtual.options.overwrite) {
    sch.virtual(key, virtual.options);
  } else {
    if (virtual.get) { // else path not taken
      sch.virtual(key, virtual.options).get(virtual.get);
    }

    if (virtual.set) { // else path not taken
      sch.virtual(key, virtual.options).set(virtual.set);
    }
  }
}
```
why is this marked as "else path not taken" when there is simply nothing todo in an else path (because `sch.virtual(key, virtual.options).set(undefined);` or "null" would not be accepted by the function)

**Comment by vctormb** [comment]
My workaround is doing like this:

```
function handleChange() {
  if (!props.onChange) return;

  props.onChange('value');
}
````

And then I test it without the `onChange` prop.

**Comment by jt3k** [comment]
it is sad

Does anyone here know about the existence of a plugin that could add sorting capability to Atom?

**Comment by Jimmydalecleveland** [comment]
I was pretty annoyed with this error and the debate in the thread until I read this comment https://github.com/gotwarlost/istanbul/issues/35#issuecomment-397301354 from @andreyluiz .

Since most linters I've used do not want you to have unnecessary return statements, doing something like:
```js
if (isTrue) {
  doSomething()
}
return
```

is not feasible. I thought that was what was being advised until the previous comment, when I realized I'm just supposed to actually test the event in which the if statement does not pass (e.g. `isTrue` === false). This makes a lot more sense to me, and I find the rule very helpful so thank you to everyone who debated about this.

**Comment by rajeshrasch** [comment]
**Change something with only if statement to**
` onKeyDown={event => {
                            if (this.state.shouldClose && event.keyCode === ECS_KEY) {
                                this.setState({
                                    toShow: false,
                                });
                            }
                        }}`
**To this with shortand**
` onKeyDown={event => {
                             (this.state.shouldClose && event.keyCode === ECS_KEY) && 
                                 this.setState({
                                     toShow: false,
                                 })
                        }}`

**Comment by MrBrN197** [comment]
I've read through this entire discussion trying to understand why this makes sense and why my branch coverage wasn't 100% regardless of how many tests I wrote. like @Jimmydalecleveland said about the former comment. it really is just about explicitly testing the "branches" in your code. even if it does nothing explicitly testing that, is necessary.

**Comment by Serzhs** [comment]
Consider this as a jest bug and add `/* istanbul ignore else */` on top of your if
