### ISSUE TITLE
Documentation of coverage.json

### ISSUE THREAD

**Issue by stevepeak** [gotwarlost/istanbul#354]
Hey, I'm looking for some docs on understanding the `coverage.json` file produced so that I can get partial coverage properly working on [Codecov](https://codecov.io).

The content of this document seems to have strange values that I cannot make out at this moment. Here is an example of two projects that have uploaded reports to. [eddiemoore/es6api](https://codecov.io/github/eddiemoore/es6api/app/routes/users.js?ref=8f6a5fd593fc96b086634a7bff103e3109a63dec) and [cainus/codecov.io](https://codecov.io/github/cainus/codecov.io/lib/services/travis.js?ref=a2308f6f83c615267b41c3ce08bdef70d43b6b08).

I have the actual `coverage.json` data to review if necessary. 

Thank you for your time!

**Comment by gotwarlost** [comment]
This is a very good description of the coverage object: https://github.com/gotwarlost/istanbul/issues/295

See the comment by @jwalton

**Comment by jwalton** [comment]
I have a slightly updated version of this [here](https://github.com/benbria/coffee-coverage/blob/master/src/instrumentors/Istanbul.coffee).  (I think the biggest change in this version is I describe how the `ignore` pragmas work, there might be one or two minor corrections from me implementing all this stuff.)  I'll extract this into a markdown file later today and submit it as a PR to istanbul.

**Comment by jwalton** [comment]
One other thing I'm missing in this description, actually: the `skip` for a function goes strait into the `fnMap` object, not into the location.

**Comment by jwalton** [comment]
https://github.com/gotwarlost/istanbul/pull/355

**Comment by jwalton** [comment]
@stevepeak Just gave codecov a try with coffee-coverage.  I get [very different results from codecov](https://codecov.io/github/benbria/coffee-coverage) than I do from Istanbul or [coveralls](https://coveralls.io/builds/2487317).  This what you're working on, then?  :)

**Comment by stevepeak** [comment]
@jwalton yes, It works well for `lcov` uploads, but since I can do partial coverage I figured to add that support. But I'm it looks like I'm not parsing the document correctly. Thank you for showing me the documentation, I'll review it and get back to you with my progress.

**Comment by davglass** [comment]
Fixed in #355
