### ISSUE TITLE
Coverage of actual tests in the test/spec-files

### ISSUE THREAD

**Issue by hacker112** [gotwarlost/istanbul#367]
Is it possible to include the coverage of the tests that are run?

It would be very helpful to see that all lines in the tests have been run, since dead code in the tests could mean that parts of tests are never run. (which happened to me today)

**Comment by davglass** [comment]
Yup, it's pretty easy:

`istanbul cover --no-default-excludes -x "**/node_modules/**" <insert your tests here>`

By default `istanbul` excludes the following: `[ **/node_modules/**, **/test/**, **/tests/** ]`

We turn that off with `--no-default-excludes`, then turn on the exclude for the dependencies with `-x "**/node_modules/**"`, then add your test runner after it and you should see the tests being covered.

I have a few apps that I don't exclude the node_modules directory during functional testing to ensure that I am using as much of my dependencies as possible. I've been able to move to smaller modules once I noticed that I am only using certain parts of certain larger modules.

**Comment by hacker112** [comment]
Awesome! I found some errors in my test with that. Thanks a lot!
