### ISSUE TITLE
What is default ignored directory name?

### ISSUE THREAD

**Issue by falsandtru** [gotwarlost/istanbul#370]
Can I release ignored by command line options?

**Comment by gotwarlost** [comment]
yes, if I understand what you are trying to ask. Use the `--no-default-excludes` option

**Comment by falsandtru** [comment]
Thanks!
Is there a document that API? I was looking for this repository but could not be found.
After that, please tell me the default ignored directory name. Is there a directory that will be ignored other than `test` directory?

**Comment by gotwarlost** [comment]
`istanbul help cover` will give you that information

**Comment by falsandtru** [comment]
Sorry, I did not recognize that I can specify the command after the `help`. Thanks.
