### ISSUE TITLE
Get failed if include-all-sources is enabled with a directory calls 'somthing.js'

### ISSUE THREAD

**Issue by yurenju** [gotwarlost/istanbul#375]
**Description**

Getting error from command `istanbul cover index.js` if there is a directory name with `.js` and enable `include-all-sources`.

**Steps to reproduce**

1. `git clone https://github.com/yurenju/istanbul-dir.js-testcase.git`
2. `istanbul cover index.js`

**Expected**

Get coverage report includes all sources

**Actually**

Get errors:

```
Loading config: /Users/yurenju/src/istanbul-dir.js-testcase/.istanbul.yml
3

fs.js:487
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:487:19)
    at Object.fs.readFileSync (fs.js:321:28)
    at /Users/yurenju/.nvm/v0.10.31/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:221:48
    at Array.forEach (native)
    at process.<anonymous> (/Users/yurenju/.nvm/v0.10.31/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:219:39)
    at process.g (events.js:180:16)
    at process.emit (events.js:95:17)
```

**Investigation**

`fileset` module which is used in [file-matcher.js#L30-L33](https://github.com/gotwarlost/istanbul/blob/master/lib/util/file-matcher.js#L30-L33) should accept `nodir` option to exclude directories with `.js`, but `fileset` module uses old version of [glob](https://github.com/isaacs/node-glob) which does not support this option.

**Possible solution**

[Solution 1]

:white_check_mark: - Send a [pull request](https://github.com/mklabs/node-fileset/pull/14) to fileset to upgrade glob -- done but does not get response yet for few weeks
:white_medium_square: - Send a pull request to istanbul if fileset is patched.

[Other solutions]
1. Fork fileset
2. Deprecate `fileset` and write the same feature in istanbul.

**Comment by davglass** [comment]
I'm not sure I follow what this issue is for, `mocha cover index.js` isn't an `istanbul` command, it's a `mocha` command. Can you please explain a little more on what you are trying to accomplish here?

**Comment by yurenju** [comment]
@davglass, my apology, it should be `istanbul cover index.js` and I also modified description.

I got error from istanbul if there is a directory with `.js`, after investigation I found the root cause is in file-matcher.js, we use `'**/*.js'` to get all javascript files so the directory with `.js` will be read as a file.

```
Error: EISDIR, illegal operation on a directory
```

to fix it, we should use `{nodir: true}` to exclude directory which just like what I patched on [my repository](https://github.com/yurenju/istanbul/commit/9898dbd619fa08840a00a4515b6054e1e774a80f).

to accomplish this, we also have to upgrade node-glob from 3.x to 5.0 for `fileset` module, so I create another pull request on [fileset](https://github.com/mklabs/node-fileset/pull/14)

please let me know if you need more information :D

**Comment by davglass** [comment]
Thanks, that makes more sense :)

**Comment by mklabs** [comment]
Hi all and sorry for the delay

@yurenju should have fixed the issue with the PR and I just bumped fileset to 0.1.6. Thanks @yurenju

**Comment by yurenju** [comment]
although we have a pull request for this issue, but we still discuss versioning issue for [fileset](https://github.com/mklabs/node-fileset/pull/14)

**Comment by mklabs** [comment]
Hello there,

As I mentioned in mklabs/node-fileset#14, I'll probably bump a 0.2.x version.

@davglass Istanbul still supports 0.8 as I can see in your [.travis.yml](https://github.com/gotwarlost/istanbul/blob/master/.travis.yml#L3) ? If so, I had some issue applying @yurenju PR without breaking installs on systems with node 0.8.x.

My plan is to revert the change and bump a new 0.1.x version. 0.2.x will include @yurenju fix along a synchronous API as glob supports it. Might be handy.

Regards,
Mickael
