### ISSUE TITLE
Trying to pass Istanbul report to Travis, but the coverage report's location is too unpredictable

### ISSUE THREAD

**Issue by BlackBaud-AlanGordon** [gotwarlost/istanbul#380]
I'm using Istanbul to generate code coverage reports, and I want to configure a Travis CI build to generate the code coverage report and send it to Code Climate. Travis's instructions say the command to run after the script is `codeclimate < lcov.info`, but the part I'm having trouble with is the file's location. It's not `./lcov.info`, and it's not `./coverage/lcov.info`, it's `./coverage/PhantomJS 1.9.8 (Windows 7 0.0.0)/lcov.info`. On the Travis build server, it's `./coverage/PhantomJS 1.9.8 (Linux 0.0.0)/lcov.info`. If I upgraded to a new version of PhantomJS, I assume it would change the directory here, too.

Is there a way to configure Istanbul to always place the lcov.info file in the same place, instead of moving it based on the browser and OS? If not, is there a way to programatically get the real location of the file?

**Comment by gotwarlost** [comment]
Are you using `karma` by any chance? It is the karma pre-processor that generates the dynamic subdirectory based on the browser being tested. It's not an istanbul problem.

**Comment by MarkPThomas** [comment]
A bit late, but to save anyone else searching about this from being disappointed landing on this page, karma-coverage has a workaround, by specifying the subdir element in the reporters definition to place reports in a constant location.

See:
https://github.com/karma-runner/karma-coverage/issues/61
https://github.com/karma-runner/karma-coverage/pull/62

Usage (see 'Advanced, multiple reporters'):
https://github.com/karma-runner/karma-coverage
