### ISSUE TITLE
coffeescript ignore coverage doesn't work

### ISSUE THREAD

**Issue by artmees** [gotwarlost/istanbul#382]
in the following example

    ### istanbul ignore else ###
    toast.error response.data.title if response.data

the coverage reporter doesn't ignore the else path
resulting in the following 
![screen shot 2015-05-27 at 11 20 50 pm](https://cloud.githubusercontent.com/assets/347712/7847896/78df3a44-04cf-11e5-9ffa-10be8b14d57d.png)

I've tried to change the code and the comment in many various ways but non of them worked... I'm wondering if ignore path is working at all ?!

**Comment by gotwarlost** [comment]
the coffeescript is most likely compiling down to JS that doesn't have an `if` condition just after the ignore comment.

**Comment by artmees** [comment]
Actually it doesn't work with any code... for example I've changed the code to be

```coffee
    ### istanbul ignore else ###
    if response.data and response.data.title
      toast.error response.data.title
```

which compiles to the following java script
```js
    /* istanbul ignore else */
    if (response.data && response.data.title) {
      toast.error(response.data.title);
    }
```

and it doesn't work either...

![screen shot 2015-06-11 at 4 58 49 am](https://cloud.githubusercontent.com/assets/347712/8098939/efc8c0e6-0ffe-11e5-9451-bb5e66f8879e.png)
