### ISSUE TITLE
File merge code assumes that all coverage objects contain all lines

### ISSUE THREAD

**Issue by sh1mmer** [gotwarlost/istanbul#402]
The `mergeFileCoverage` function has a couple of bad assumptions in it.

```javascript
    function mergeFileCoverage(first, second) {
        var ret = JSON.parse(JSON.stringify(first)),
            i;

        delete ret.l; //remove derived info

        Object.keys(second.s).forEach(function (k) {
            ret.s[k] += second.s[k];
        });
        Object.keys(second.f).forEach(function (k) {
            ret.f[k] += second.f[k];
        });
        console.log(ret);
        Object.keys(second.b).forEach(function (k) {
            var retArray = ret.b[k],
                secondArray = second.b[k];
            for (i = 0; i < retArray.length; i += 1) {
                retArray[i] += secondArray[i];
            }
        });

        return ret;
    }
```

Here is an example of a real merge

```javascript
{ path: '/Users/sh1mmer/example.js',
  s: { '1': 1, '2': 1, '3': 1, '4': 1 },
  b: {},
  f: {},
  fnMap: {},
  statementMap:
   { '1': { start: [Object], end: [Object] },
     '2': { start: [Object], end: [Object] },
     '3': { start: [Object], end: [Object] },
     '4': { start: [Object], end: [Object] } },
  branchMap: {} } { path: '/Users/sh1mmer/example.js',
  s: { '1': 1, '2': 1, '3': 1, '4': 1, '5': 1 },
  b: {},
  f: {},
  fnMap: {},
  statementMap:
   { '1': { start: [Object], end: [Object] },
     '2': { start: [Object], end: [Object] },
     '3': { start: [Object], end: [Object] },
     '4': { start: [Object], end: [Object] },
     '5': { start: [Object], end: [Object] } },
  branchMap: {} }
{ path: '/Users/sh1mmer/example.js',
  s: { '1': 2, '2': 2, '3': 2, '4': 2, '5': NaN },
  b: {},
  f: {},
  fnMap: {},
  statementMap:
   { '1': { start: [Object], end: [Object] },
     '2': { start: [Object], end: [Object] },
     '3': { start: [Object], end: [Object] },
     '4': { start: [Object], end: [Object] } },
  branchMap: {} }
```

Since the first coverage object didn't contain all of the statements `+=` just produces NaN results. The most pathological case is branch coverage merging which sometimes just causes uncaught exceptions trying to access the length of an array which is undefined.

I'd suggest we can fix this by updating the function to:

```javascript
    function mergeFileCoverage(first, second) {
        var ret = JSON.parse(JSON.stringify(first)),
            i;

        delete ret.l; //remove derived info

        Object.keys(second.s).forEach(function (k) {
            ret.s[k] = (ret.s[k]) ? ret.s[k] + second.s[k] : second.s[k];
        });
        Object.keys(second.f).forEach(function (k) {
            ret.f[k] = (ret.f[k]) ? ret.f[k] + second.f[k] : second.f[k];
        });
        console.log(ret);
        Object.keys(second.b).forEach(function (k) {
            var retArray = ret.b[k] || [],
                secondArray = second.b[k];
            for (i = 0; i < retArray.length; i += 1) {
                retArray[i] += secondArray[i];
            }
        });

        return ret;
    }
```

cc @Matt-Esch

**Comment by gotwarlost** [comment]
Can you tell me why the shape of the coverage object could be different for the same file?

**Comment by blond** [comment]
+1

**Comment by gotwarlost** [comment]
Unless someone gives me a really good reason as to why the shape of the coverage object should be different for the same file, I'm closing this. Feel free to reopen with an explanation of how this could happen

**Comment by sh1mmer** [comment]
@gotwarlost this actually happens on our test runs. I wasn't just looking for random things to fix.

I'm going to guess it is because multiple different test runs exercise different paths in the file so some of them are more complete than others, or just different.

Are you saying that that `require` would always generate the full map no matter what?

**Comment by gotwarlost** [comment]
Yes. The _shape_ of the coverage object should not change with test runs - only hits do. If you are having issues with stuff not found in the map, it means that you are trying to merge coverage objects with different signatures for the same filename.

**Comment by jedwards1211** [comment]
@sh1mmer @blond were you guys seeing this when trying to merge coverage from client and server code?
I'm generating coverage on an isomorphic app where some files run in both the client and server, but different blocks run depending on whether it's client or server.  I'm not seeing this issue, but I'm not sure the coverage is getting merged properly...

**Comment by jedwards1211** [comment]
@gotwarlost I have seen coverage objects change because I added some code to a source file during tests to test hot reloading.  Probably not a valid use case, but it is a case where the shape of the coverage object changes.  I had to exclude those test cases during coverage runs to get everything to work.

**Comment by morungos** [comment]
I'm seeing replicable errors in precisely this code. This happens when I use the `json-summary` report. First time it works fine. Second time (which seems to involve generation of *any* report, not ncessarily a `json-summary`, it always throws an error: 

```
/usr/lib/turalt-ci/data/projects/turalt-public/workspace/node_modules/istanbul/lib/object-utils.js:239
            ret.s[k] += second.s[k];
                 ^

TypeError: Cannot read property '1' of undefined
```

This could be an issue in the JSON summary report generation, but it's definitely also in this piece of code. 

This might be better as a separate issue, I don't know the code well enough to judge. But it's in the same function, and feels likely linked.
