### ISSUE TITLE
Add ability to remove visited link color

### ISSUE THREAD

**Issue by sgerace** [gotwarlost/istanbul#404]
In v0.3.15 a visited link color was added to the css. I'm not sure about anybody else, but for me, I find it distracting to see a different color for some of the coverage files vs others, simply on the basis of whether or not I've visited the page. Even worse, is that over time all of the links become visited (since I'm navigating through the various coverage files) which is far less appealing than the default black links. 

For now I've simply gone into by `node_modules` folder and switched the color on `a:visited` elements back to the default `#000`, however, it would be nice if there was a way to accomplish this that would persist across `npm installs`.

**Comment by gotwarlost** [comment]
The HTML template has completely changed with v0.4 - is this still a problem? Reopen if so.

**Comment by sgerace** [comment]
The new style addresses the issue (and looks great, btw), thanks!
