### ISSUE TITLE
Couldn't find the difference between line and statement coverage?

### ISSUE THREAD

**Issue by kawaljeetdhesi** [gotwarlost/istanbul#407]
![coveragereport](https://cloud.githubusercontent.com/assets/7125237/8750274/87f2c614-2c74-11e5-9cfd-f96c25a8cd12.png)

The result for both line and statement coverage comes always same. I didn't find any appropriate answer for this question.

If both are same, then is there any option to get only one ether line or coverage to avoid the confusion?

**Comment by gotwarlost** [comment]
It can only be different of you have more than one statement on one line. Statement coverage is a more accurate indicator of coverage - line coverage is to support existing coverage tools that rely on line level info
