### ISSUE TITLE
istanbul dislikes super keyword (ES6)

### ISSUE THREAD

**Issue by kkragenbrink** [gotwarlost/istanbul#414]
Gist: https://gist.github.com/kkragenbrink/1322bd296140bf15ace6

Seems istanbul has an issue with the super keyword.

**Comment by kkragenbrink** [comment]
This seems to be resolved by the istanbul-harmony branch.

**Comment by sterlinghw** [comment]
+1

This causes the file containing `super` to not be reported on. Also, the istanbul-harmony branch does not work for me. It appears to have more issues than just running `master`

**Comment by whitingj** [comment]
+1
This should be in master.

**Comment by mermaid** [comment]
definite +1 for me as well

**Comment by sterlinghw** [comment]
PR incoming

**Comment by ronkorving** [comment]
Looking forward to it :+1:

**Comment by Fantus** [comment]
+1

**Comment by xFragger** [comment]
+1 ... waiting for this, too

**Comment by ronkorving** [comment]
It's already been released :)

**Comment by xFragger** [comment]
yeah, sorry.... than, what about closing this?

**Comment by gotwarlost** [comment]
I believe this is fixed?

**Comment by sterlinghw** [comment]
Yup, fixed.
