### ISSUE TITLE
Coffeescript support

### ISSUE THREAD

**Issue by turadg** [gotwarlost/istanbul#43]
Thanks for Istanbul, which I'm using in a Rails app with [Teabag](https://github.com/modeset/teabag).  Though it's a Rails app, I have lots of Javascript code for a Backbone app, and that's mostly in Coffeescript.

Is it possible or planned for Istanbul to report lines numbers on Coffescript source?

It looks like [jasmine-coverage-javascript-coffeescript](https://github.com/meismann/jasmine-coverage-javascript-coffeescript) is part of the way there, using [coffee-coverage](https://npmjs.org/package/coffee-coverage).

**Comment by boiawang** [comment]
+1

**Comment by Zolmeister** [comment]
+1

**Comment by DecipherCode** [comment]
+1

**Comment by itsjustcon** [comment]
+1
