### ISSUE TITLE
Option to not instrument (not "ignore" but just not instrument it at all)

### ISSUE THREAD

**Issue by mehcode** [gotwarlost/istanbul#433]
I'm using [phantomjs-node](https://github.com/sgentle/phantomjs-node) and during the `evaluate` call the function I use has `.toString` called on it and passed into the browser context. It then complains that it cannot find the tracking variables for code coverage.

```js
var phantom = require('phantom');

phantom.create(function (ph) {
  ph.createPage(function (page) {
    page.open("http://www.google.com", function (status) {
      console.log("opened google? ", status);
      page.evaluate(function () { return document.title; }, function (result) {
        console.log('Page title is ' + result);
        ph.exit();
      });
    });
  });
});
```

---

I'm looking for a way to have that anonymous function passed into `evaluate` not instrumented and ignored.

**Comment by ironwallaby** [comment]
I, too, would like an option for not instrumenting a given function or loop. In my case, I'm doing image manipulation, and the instrumentation adds so much overhead that code that would take a couple milliseconds now takes several seconds, causing my tests to time out.

**Comment by gotwarlost** [comment]
I'm working on the next version of the instrumenter which will do away with injecting code into places that it has been asked not to instrument. It won't be an option - it will just be the way the instrumenter works. Creating an option would mean maintaining a fork across a complex code path. There is no simple fix for this problem as it stands. Stay tuned.
