### ISSUE TITLE
Redesign?

### ISSUE THREAD

**Issue by tmcw** [gotwarlost/istanbul#434]
I'm interested in spending a bit of time with istanbul to give it a fresh coat of paint. It's definitely primarily a utilitarian tool, but I feel like a bit of design love would go a long way in making our daily code coverage experiences more enjoyable.

Would the project be open to this kind of contribution? My goal would be to keep the same content but structure it more and bring it more in line with current design.

**Comment by davglass** [comment]
:+1:

**Comment by douglasduteil** [comment]
+1

**Comment by lo1tuma** [comment]
:+1:

**Comment by gotwarlost** [comment]
Closing this issue since we will be merging the redesign shortly.
