### ISSUE TITLE
What is _mocha?

### ISSUE THREAD

**Issue by gajus** [gotwarlost/istanbul#436]
The only way I managed to make istanbul work is using `./node_modules/.bin/_mocha`.

```sh
# works
babel-node node_modules/.bin/istanbul cover _mocha -- test

# does not work
babel-node node_modules/.bin/istanbul cover mocha -- test
```

However, it cannot find where it is documented. I have only found it mentioned in issues such as this, https://github.com/gotwarlost/istanbul/issues/44.

**Comment by apowers313** [comment]
`mocha` is a wrapper for `_mocha` -- all the real work happens in `_mocha`. Here's a link to the [Mocha executables code](https://github.com/mochajs/mocha/tree/master/bin). Maybe that helps?

**Comment by gotwarlost** [comment]
what @apowers313 said.

**Comment by vdegenne** [comment]
using `./node_modules/.bin/_mocha` instead of `./node_modules/.bin/mocha` in the debug properties in `vscode` helped the debugger to stop at my breakpoints, otherwise it would ignore them. Just wanted to share that information.

**Comment by basickarl** [comment]
Any update on this? mocha is still broken with breakpoints.
