### ISSUE TITLE
Configuring istanbul with mocha

### ISSUE THREAD

**Issue by dankohn** [gotwarlost/istanbul#44]
Istanbul works flawlessly with jasmine-node, using the command: `istanbul cover jasmine-node test'

Is it possible to use istanbul with mocha, in a similar way. I get the following:

```
$ istanbul cover mocha -u exports -R spec

fs.js:684
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'exports.js'
    at Object.fs.statSync (fs.js:684:18)
    at lookupFiles (/usr/local/share/npm/lib/node_modules/mocha/bin/_mocha:390:17)
    at spinner (/usr/local/share/npm/lib/node_modules/mocha/bin/_mocha:268:24)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/mocha/bin/_mocha:267:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
No coverage information was collected, exit without writing coverage information
```

I tried using https://github.com/arikon/mocha-istanbul as the reporter but got a similar error.

**Comment by ublue1024** [comment]
Thank you, #44 also solved my problem. In Windows 7, I just use 
istanbul cover {my_npm_path}\node_modules\mocha\bin\_mocha

**Comment by otuome** [comment]
hey @gotwarlost, i'm on osx 10 and running the following script for a simple express app via `npm test` results in _"No coverage information was collected, exit without writing coverage information"_ even though the tests run successfully: 

`istanbul cover _mocha -- -R tap \"test/*-test.js\"`

what's the best way to debug the reason that coverage.json is not being generated?

curious b/c the following does generate a coverage.json, as well as, the CLI summary output:

`istanbul cover app.js`

**Comment by hariharan93m** [comment]
Thanks @otuome

**Comment by Om-sudhir** [comment]
Hi Team,
Even we tried with full path in windows 7 m/c ,id doesn't works. All Tests were executed and passed ,No coverage information was collected, exit without writing coverage information.

istanbul cover C:\Users\user_sam\AppData\Roaming\npm\node_modules\mocha\bin\mocha -- -R spec 
-----------------------
D:\BaseRepo3\FirstNodejsWebApp>istanbul cover D:\KBaseRepo3\FirstNodejsWebApp\node_modules\mocha\bin\_mocha -- -R spec


  KB unit test
    V should return all article (91ms)
    V should return home Page (173ms)
    V should return article by TagName
    V should return article by ID
UnitTestTag  added  to the article with id = 564d9eddd33338af2dd709d
    V should add newtag by iD AND TAG
    V should list all the available TAGs
    V should list of top 5 articles
    V should list articles matching all tags


  8 passing (785ms)

No coverage information was collected, exit without writing coverage information
-----------------


Please help!!

**Comment by xjamundx** [comment]
@Om-sudhir try linking to the `_mocha` file instead of `mocha`

**Comment by ORESoftware** [comment]
Just saying - it would be a lot cooler if mocha tests could be run with the plain old Node executable.

**Comment by xjamundx** [comment]
@ORESoftware you can use https://github.com/bcoe/nyc for that and it works really well!

**Comment by ndaidong** [comment]
@xjamundx thanks.

My problem with **istanbul** is it does not return any coverage info. "No coverage information was collected, exit without writing coverage information."

I've just install **nyc** and it works for me. Now I have needed info within ".nyc_output", and if I run `nyc report --reporter=lcov` it will generate "coverage" folder like what **istanbul** should does.

**Comment by robwilkerson** [comment]
I'm stumped. I'm running `istanbul@0.4.3` and `mocha@2.4.5`. My `mocha.opts` file includes the `--harmony_destructuring` flag.  Running `npm test` executes this script:

    sudo -u www-data NODE_ENV=test mocha

The tests execute exactly as expected. When I execute the coverage script, though, I always get an unknown option error:

> error: unknown option `--harmony_destructuring'

I've tried each of the following:

    $ NODE_ENV=test node --harmony node_modules/istanbul/lib/cli.js cover node_modules/.bin/_mocha
    $ NODE_ENV=test istanbul cover node_modules/.bin/_mocha

What am I doing wrong here?

**Comment by robwilkerson** [comment]
Argh. Punitive headslap. I just realized someone had put the flag back in `mocha.opts` and the flag sent to mocha was throwing the error, of course. Apologies for any confusion. The following works just fine as long as the harmony flags are removed from `mocha.opts`:

    NODE_ENV=test node --harmony_destructuring node_modules/istanbul/lib/cli.js cover node_modules/.bin/_mocha

**Comment by FrankChinedu** [comment]
> istanbul cover _mocha

No coverage information was collected, exit without writing coverage information
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                                                                             ^^^^

SyntaxError: Unexpected identifier
