### ISSUE TITLE
Loading config message in forked instances

### ISSUE THREAD

**Issue by asa-git** [gotwarlost/istanbul#440]
Hi,
I was adding the required update to my library to allow coverage of forked node instances and noticed that each instance was displaying on the console the fact that istanbul was loading its configuration from a file.

I could silence this output by using the silent option of my forked process, but looking at the source of istanbul, I was wondering if it was a console forgotten by mistake ?

The line seems to be here: https://github.com/gotwarlost/istanbul/blob/master/lib/config.js#L425 

Could that output be removed or at least made optional (via the verbose argument maybe) ?

Thanks in advance.

**Comment by gotwarlost** [comment]
Do you want to send a PR for this? Seems fair that the line should only be printed in verbose mode.

**Comment by asa-git** [comment]
Sure, I'll do it tonight after work.

**Comment by asa-git** [comment]
done: https://github.com/gotwarlost/istanbul/pull/442
thanks.

**Comment by gotwarlost** [comment]
Merged.

**Comment by asa-git** [comment]
tks !
