### ISSUE TITLE
bump handlebars dependency version (security)

### ISSUE THREAD

**Issue by konobi** [gotwarlost/istanbul#447]
The current dependency version of handlebars uses an insecure version of uglifyJS (see https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons).

You should bump the current handlebars version to ensure that a secure version of uglifyJS is used.

**Comment by chetanddesai** [comment]
FYI, handlebars updated fixed this in `v4.0.0` ([commit](https://github.com/wycats/handlebars.js/commit/9d4353c35cc93cbc44125efcb2c4d348cb51cf06)).  So anything after 4.0.0 should be good.

**Comment by konobi** [comment]
Yup... just need to bump the dependency version of handlebars in "istanbul" to ensure that is the one that is installed.

**Comment by davglass** [comment]
PR: #431
