### ISSUE TITLE
HTML report labels and meanings

### ISSUE THREAD

**Issue by goncalvesjoao** [gotwarlost/istanbul#450]
Hi guys.

I'm a little confused what does the yellow and gray marks represent and what is the missing lines of code that are not covered in this example?

![Html report of a simple react component](https://dl.dropboxusercontent.com/u/5290755/html-report.png)

Thanks in advance!

**Comment by madbence** [comment]
@goncalvesjoao it's weird, but imho the code here is the compiled one (i guess it's compiled from jsx?), but the coverage info belongs to the original code.

**Comment by goncalvesjoao** [comment]
That would explain a lot, thanks @madbence!
