### ISSUE TITLE
Need to lift node related arguments

### ISSUE THREAD

**Issue by dotnil** [gotwarlost/istanbul#454]
When testing codes that use experimental JavaScript syntaxes hide behind flags, we need to pass arguments like `--harmony`, `--harmony_arrow_functions` to node. In mocha the node related arguments are lifted if passed. So commands like:

```bash
$ mocha --harmony --timeout 5000 test/*.js
```

Will be expanded as 

```bash
$ node --harmony _mocha --timeout 5000 test/*.js
```

This allows `test/*.js` be able to use experimental JavaScript syntaxes. 

But currently in the way istanbul supports mocha, this is not achievable. Commands like this can run successfully, but istanbul won't be able to collect any info because the code is executed in another process:

```bash
$ istanbul cover mocha --harmony --timeout 5000 test/*.js
```

The commands recommended in other issues won't run because the node related arguments like `--harmony` is passed to `_mocha` rather than `node`.

```bash
$ istanbule cover _mocha --harmony --timeout 5000 test/*.js
$ node _mocha --harmony --timeout 5000 test/*.js    # the one spawn by istanbul
```

I'll submit a PR if someone can confirm this bug. Or is there other ways to work around this?

**Comment by gotwarlost** [comment]
Run istanbul itself under `node --harmony` - instead of `istanbul cover` do `node --harmony /path/to/istanbul/cli.js` and then the `_mocha` command doesn't need to know about harmony.

**Comment by dotnil** [comment]
Indeed. thx
