### ISSUE TITLE
How I can get the if/else flow for those variables that are defined inside the 

### ISSUE THREAD

**Issue by web20opensource** [gotwarlost/istanbul#459]
How can I increase the coverage in the case a condition depends on a variable that is defined inside the same scope ? So the variable always will return undefined for the first iteration but will have a value in the second iteration... But seems Istanbul is not able to see it...

I'm sure this is not an issue but I don't know if there's a way without modify the original code to reach a greater coverage...

![notcovered](https://cloud.githubusercontent.com/assets/2625752/10228504/b9b5591e-6838-11e5-85f2-ca638e426f1f.png)

**Comment by gotwarlost** [comment]
I don't follow. What's the problem? If you had a test case that passed in more than one `receiveOption` it would get covered?

**Comment by web20opensource** [comment]
I'm not sure if there's an issue. Might be I'm superb newbie in Istanbul.

The variables are immediately created inside the function scope. And even
the receiveOption has too many options and is being assigned into the
selectedOption and selectedGroup .... The code is stilll shown as not
covered so meaning is not being executed, right?

**Comment by web20opensource** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend web2.0opensource has been using DigitalOcean – a cloud
hosting service designed just for developers – and thought you might want
to give it a shot. You can deploy a server in 55 seconds from our control
panel or use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=19d5aed7d114be&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>
