### ISSUE TITLE
exclude or ignore a test

### ISSUE THREAD

**Issue by thisconnect** [gotwarlost/istanbul#469]
I use `istanbul cover test/test.js`. One of the tests checks if all functions are below 600 chars (https://top.fse.guru/nodejs-a-quick-optimization-advice-7353b820c92e#.ytqibx71s). If they are run though istanbul they blow up and are all above 600 chars and fail. I would like to exclude this test from being run through istanbul.

There is `/* istanbul ignore next */`but this only works in the source, but not in the tests. Is there anyway to exclude or ignore some of the tests?

**Comment by gotwarlost** [comment]
No. istanbul is not a test runner.

**Comment by thisconnect** [comment]
Ok, in this case I duplicate my test.js entry point and just all the other tests beside the one that checks the function.
