### ISSUE TITLE
HTML report on instrumented code

### ISSUE THREAD

**Issue by brandybuck** [gotwarlost/istanbul#471]
We used istanbul instrumenter to instrument all our source code before production. While its running in production, it will collect the __coverage__ object and periodically post it to a node.js server.

In the node.js server we use Istanbul reporter to derive HTML reports out of the __coverage__ object. But the report is constructed on instrumented code. Can the reporter remove the istanbul instrumentation?

Or how is it possible for me to introduce instrumentation in the original code and derive a HTML report which will show me the coverage in the un-instrumented JS code?

**Comment by gotwarlost** [comment]
Are you instrumenting the code in place (overwriting I mean). If your original sources are in say `src/` and you instrument them into `src-instrumented/` then the coverage object will have correct paths and use the correct files for the HTML report (assuming the files under `src/` are still available at report generation).

**Comment by gotwarlost** [comment]
Reopen if this doesn't answer your question
