### ISSUE TITLE
multiple tests with tape

### ISSUE THREAD

**Issue by tcurdt** [gotwarlost/istanbul#472]
I am using [tape](https://github.com/substack/tape) for testing. Running all tests is done with `tape tests/*.js` but `istanbul test tests/*.js` is only the equivalent of `node tests/*.js` which only runs the first test.

Any suggestions?

**Comment by tcurdt** [comment]
Actually - nevermind. Seems like `istanbul test tape -- tests/*.js` works.

**Comment by 75lb** [comment]
thanks ;)
