### ISSUE TITLE
Generate LCOV file

### ISSUE THREAD

**Issue by xseignard** [gotwarlost/istanbul#48]
Hi, I'm investigating code coverage for node.js code.

You'll may find this dumb, but I cannot figure out on how to generate lcov file (i.e. format described here: http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php).

Something like this:

```
SF:core/calculator.js
DA:1,1
DA:2,1
DA:10,2
DA:11,2
DA:14,2
DA:20,1
end_of_record
```

I use a quality dashboard (http://www.sonarsource.org/) to display code quality metrics. And lcov format is the only one accepted.

Regards.

Xavier

**Comment by vldmr1986** [comment]
So, how to generate report.lcov  ???
? any suggestions

I use Jest for testing, but as I understand I need to install Istanbul, if anybody has manual plz help
