### ISSUE TITLE
Transpiling but gets not test coverage

### ISSUE THREAD

**Issue by kennetpostigo** [gotwarlost/istanbul#484]
I get the following error:
<img width="921" alt="screen shot 2015-11-15 at 12 49 56 am" src="https://cloud.githubusercontent.com/assets/8888991/11167514/d82990be-8b32-11e5-9efc-2016543e43ae.png">

Im currently using mocha with babel and istanbul.

This is my test script:
<img width="639" alt="screen shot 2015-11-15 at 12 46 22 am" src="https://cloud.githubusercontent.com/assets/8888991/11167505/56027272-8b32-11e5-93b3-6ea219e3e922.png">

This is my script for coverage maintanence:
<img width="557" alt="screen shot 2015-11-15 at 12 47 05 am" src="https://cloud.githubusercontent.com/assets/8888991/11167507/69bc85d2-8b32-11e5-9ca7-c6e1a4bdf79a.png">

This is my script for reporting coverage to codecov:
<img width="334" alt="screen shot 2015-11-15 at 12 48 37 am" src="https://cloud.githubusercontent.com/assets/8888991/11167510/ad63ae78-8b32-11e5-9abe-aaa2c6701654.png">

I would appreciate all the feedback and help. New to istanbul and not sure why this is failing.

**Comment by jails** [comment]
Hi, may it be related to https://github.com/gotwarlost/istanbul/issues/485 ?
