### ISSUE TITLE
Unexpected Token Case

### ISSUE THREAD

**Issue by khrome83** [gotwarlost/istanbul#500]
Every time I run a command like - 
'node ./node_modules/.bin/istanbul check-coverage'

I get the following error -

```
C:\Users\zanem\Documents\GitHub\impressjs\node_modules\.bin\istanbul:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

If I run this with Mocha, then it reports the same issue, but states that it happening in `_mocha:4` instead.

This happens when I try to setup Istanbul to run cover over mocha. It happens when I just try and run Istanbul. I am at a loss and can't find anything about this anywhere.

Help please!

**Comment by khrome83** [comment]
Appears that the path to mocha was valid in unix but not in windows. 

`./node_modules/mocha/bin/_mocha` changing to this solved the problem. While I could call Istanbul from `./bin/Istanbul`, I could not call mocha from the same location.

**Comment by lippea** [comment]
I have the same problem. And tried with .\node_modules\.bin\_mocha, still "SyntaxError: Unexpected token case" How can I fix it?

**Comment by lippea** [comment]
Solved by running "istanbul cover node_modules\mocha\bin\mocha --  --compilers js:babel/register --recursive".

**Comment by lippea** [comment]
Finally successful by running "istanbul cover node_modules\mocha\bin\_mocha --  --compilers js:babel/register --recursive"

**Comment by CerenaNirmal** [comment]
where do you change the patch?
