### ISSUE TITLE
exclude (-x) no longer works in v1

### ISSUE THREAD

**Issue by kmudrick** [gotwarlost/istanbul#503]
Using https://github.com/istanbuljs/sample-babel-node

```
babel-node ./node_modules/istanbul/lib/cli.js cover -x notarealfile --report lcov ./test/index.test.js
```

Transformation error for /Users/kmudrick/src/sample-babel-node/index.js ; return original code
Line 17: Unexpected token
No coverage information was collected, exit without writing coverage information
/Users/kmudrick/src/sample-babel-node/index.js:3
var Animal = class {
             ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)

Removing the -x makes it work

**Comment by gotwarlost** [comment]
I don't think this is istanbul's fault. I checked how the data is getting passed in and istanbul's view of the world seems ok.

What's _most likely_ happening is that `babel-node` is interpreting the `-x` option as well  to mean

```
 -x, --extensions [extensions]  List of extensions to hook into [.es6,.js,.es,.jsx]
```

and is not applying its transforms to the es6 files. 

Reopen if you disagree
