### ISSUE TITLE
lcov.info contains filenames instead of paths for babel6-translated code

### ISSUE THREAD

**Issue by DavidPineauScality** [gotwarlost/istanbul#512]
Hi,

I'm using istanbul with babel's babel-node (version 6) to run coverage statistics collection over my unit tests.
I'm actually using the following command:
```
babel-node ./node_modules/istanbul/lib/cli.js cover ./node_modules/.bin/_mocha -- --recursive tests/unit/
```

Versions of the softwares:
 - babel ^6.0.0
 - istanbul ^1.0.0-alpha (solves an issue I had, similar to an issue I found here)

This generated a nice lcov.info file and a nice html report with the right lines reported. The issue is that when I upload lcov.info to a third-party service that needs access to my source repository (codecov.io accessing my github repository), files cannot be found due to a bad file path reported into the lcov.info file.

I tried to look into the configuration file of istanbul, hoping for a life-saving option down -there, but to no avail, since both documentation of the reporting/report-config dictionnary is a bit lacking, and I could not find any sample configuration to guide me.

I know this report is a bit vague, but I can't give access to my repository. At best, I can try to reproduce it in a more confined context/environment.

If I can do anything to help, please tell me, I'll try to provide as much information as I can.

**Comment by DavidPineauScality** [comment]
I tried generating the report from the coverage.raw.json with ```istanbul report --root coverage --dir coverage/report/``` (that contains the right paths), and this time the lcov.info file does contain the paths of the files instead of only the filenames.

I don't understand why the automatic generation does not include the file paths, could it be an internal bug ?

**Comment by jbinto** [comment]
Thanks for reporting. I am having the same issue. 

I'm attempting to do a code coverage badge on Coveralls.io. I have Istanbul coverage working with the following command:

 ```sh
babel-node ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- --recursive --require ./test/test_helper.js
```

But as you note it ouputs an `lcov.info` with `SF` parameters containing neither relative paths, nor absolute paths, but *just the filename*.

```sh
grep ^SF coverage/lcov.info
SF:constants.js
SF:game.js
SF:game_states.js
SF:utils.js
SF:validate.js
```

These files are in `/src/`, and my coveralls tool has no way to find them, it's looking for them in `./`.

I ran the command @DavidPineauScality provided, and same for me, the report-generated-from-the-report has the correct absolute path.

**Comment by jbinto** [comment]
Unfortunately, for me anyway, that only has the appearance of working.

When I edit the `lcov.info` file manually to add `src`, I get a reasonable looking code coverage report, that integrates well with Coveralls.

**Comment by jbinto** [comment]
More info:

I was able to get everything working for my project by dropping in [babel-istanbul](https://github.com/ambitioninc/babel-istanbul).

It correctly uses absolute paths and it gets the right line numbers. I'm not thrilled about using a fork but it'll do for now.

**Comment by gotwarlost** [comment]
I believe I have fixed this bug with `istanbul-lib-source-maps@1.0.0-alpha.9`. I verified the thirtyone-server project after this fix. Please try it out and let me know if this is working for you. Reopen the issue otherwise

**Comment by jbinto** [comment]
I can confirm upgrading to `istanbul-lib-source-maps@1.0.0-alpha.9` has fixed this issue for me. 

Thank you for your help @gotwarlost, much appreciated.

**Comment by gotwarlost** [comment]
You're welcome. Sorry for the delay.

**Comment by DavidPineauScality** [comment]
Hello,

This is also now working for me. Thanks !
