### ISSUE TITLE
SwitchCase branches not correctly handled

### ISSUE THREAD

**Issue by semos** [gotwarlost/istanbul#513]
If I have a ```switch case``` without ```break``` or ```return```, istanbul reports some branches to be covered even if not tested.

For example :   
```  
switch (foo) {
  case 'bar': case 'baz':
    alert(foo);
    break;
  default:
    alert('Hello !');
}
```
will become
```  
switch (foo) {
  case 'bar': 
     __cov_ezf654zfe468['b'][0][1] ++;
  case 'baz':
     __cov_ezf654zfe468['b'][0][2] ++;
    alert(foo);
    break;
  default:
    alert('Hello !');
}
```

Thus, testing the 'bar' case will validate the 'baz' case too and branch coverage statistics will be wrong.

So I propose to test the value before incrementing : 

```
switch (foo) {
  case 'bar':
    if (foo == 'bar') __cov_ezf654zfe468['b'][0][1] ++;
    alert(foo);
  case 'baz':
    if (foo == 'baz') __cov_ezf654zfe468['b'][0][2] ++;
    alert('Hello ' + foo);
    break;
}

**Comment by gotwarlost** [comment]
closing per discussion in related issue. This is not as trivial as it might seem
