### ISSUE TITLE
Using ^1.0.0-alpha.2 and generating a html report programmatically

### ISSUE THREAD

**Issue by stoffeastrom** [gotwarlost/istanbul#515]
Hi,

I'm using `^1.0.0-alpha.2` and trying to generate a html report programmatically via the `window.__coverage__` object. On the server I have this

```javascript
import { createReporter } from "istanbul-api";
import { createCoverageMap } from "istanbul-lib-coverage";

const instrumenter = createInstrumenter();
const reporter = createReporter();
reporter.add( "lcov" );

//When retrieving the `window.__coverage__`
export function writeCoverage( coverageObj ) {
  const coverageMap = createCoverageMap( coverageObj );
  reporter.write( coverageMap, {} );
}
```

This generate a html report and I can see the coverage for `All files`. However when I click on a file to check details I get the following error

```javascript
Cannot read property 'text' of undefined
TypeError: Cannot read property 'text' of undefined
    at /Users/stoffe/Dev/oribella/dev/node_modules/istanbul-reports/lib/html/annotator.js:149:53
```

Any ideas?

**Comment by stoffeastrom** [comment]
I managed to figure out why it's breaking. I'm instrumenting it in the browser so I'm using the `amd` format. However in the `instrument.instrumentSync( amd, file)` the `file` was pointing to the original source. So now I just have to figure out how I can see the file coverage of the original source and not the generated

**Comment by stoffeastrom** [comment]
Looked in the `run-cover` command and added

```javascript
const sourceMapStore = createSourceMapStore( {} );
const instrumenterOpts = {
	sourceMapUrlCallback( transformedFilePath, sourceMapUrl ) {
		sourceMapStore.registerURL( transformedFilePath, sourceMapUrl );
	}
};

const instrumenter = createInstrumenter( instrumenterOpts );
```
Now it works!

**Comment by gotwarlost** [comment]
Sorry for not getting back earlier. Have been on vacation in the past weeks. Glad you sorted it out.

**Comment by stoffeastrom** [comment]
@gotwarlost No problem! It works quite nice combining this with `browser-sync`:). My goal is to have a coverage page running in the browser that automatically updates when changing the tests.
