### ISSUE TITLE
Empty sourceRoot property in sourceMap causing source file to be expected in root of application

### ISSUE THREAD

**Issue by ChrisPearce** [gotwarlost/istanbul#516]
I am testing using v1.0.0-alpha.2.

My source map (*.js.map) files are being generated by the TypeScript compiler, and the processed files (and the supporting map files) are all being output to the same directory (i.e. /lib) as the source files.

The generated sourceMap files have an empty sourceRoot.

When Istanbul sees the empty sourceRoot property, it then looks for the source files in the root of the application rather than at the location relative to the processed file or mapping file.

**Comment by gotwarlost** [comment]
Is there a github repo I can look at to reproduce the problem? These days my day job is keeping me super busy and I'm looking for problems to be handed to me on a platter. Sorry for being such a pain.

A cursory look at the istanbul source map code tells me that most of the work is being delegated to the source maps library.But if you can set things up for me that would be really helpful.

**Comment by gotwarlost** [comment]
I just pushed out a fix for #512  - this may fix your issue as well. Please try it and let me know.

**Comment by ChrisPearce** [comment]
Many thanks.

Using istanbul-lib-source-maps v1.0.0-alpha.9 resolves this issue as well.

Are there any plans to release v1.0.0-alpha.9 to the main Istanbul repository (https://github.com/gotwarlost/istanbul) or should I just reference the  https://github.com/istanbuljs/istanbul-lib-source-maps repository for the time being?
