### ISSUE TITLE
Suggestion: having a milestone for the 1.0 release

### ISSUE THREAD

**Issue by AdrieanKhisbe** [gotwarlost/istanbul#523]
Would be interesting to have some vision about the 1.0 to come release.
(might have missed some issue).

One way could be to add a 1.0 milestne, attaching the related issue that are blocking the 1.0 release

cc https://github.com/metalsmith/metalsmith/pull/214#issuecomment-171677824

**Comment by Ajedi32** [comment]
Looks like they're using a tag for this instead of a milestone: https://github.com/gotwarlost/istanbul/labels/v1
