### ISSUE TITLE
"No coverage information was collecte" With Simple Mocha Test

### ISSUE THREAD

**Issue by machineghost** [gotwarlost/istanbul#525]
I have a pretty simple `package.json` line:

    "istanbulTest": "istanbul cover _mocha scripts/test/unit/mocha/istanbulTest.js"

With a pretty simple `istanbulTest.js`

    describe('#foo', function() {
        it('passes', function() {
            console.log('hello world');
        });
    });

However, when I try to actually `npm run istanbulTest`, my ouput is:

    > my_project@0.0.1 istanbulTest /home/me/static
    > istanbul cover _mocha scripts/test/unit/mocha/istanbulTest.js

      #foo
    hello world
        ✓ passes
    
    
      1 passing (7ms)

    No coverage information was collected, exit without writing coverage information

and no coverage files are generated.

I thought the problem might be the reporter, so I tried adding an explicit coverage reporter:

    "istanbulTest": "istanbul cover _mocha --reporter html-cov scripts/test/unit/mocha/istanbulTest.js",

However nothing changed: the test passed but no coverage report was generated.

I'm not sure if something is actually wrong with the library, or if I'm just doing something stupid (my money is on the latter), but any help would be appreciated.

Also if there was any way the library could give a more helpful message (indicating *why* no coverage files were generated), that would certainly be an improvement, though I imagine that might not be possible.

Thanks!

P.S. Here's my devDependencies, in case that matters:

    "devDependencies": {
        "chai": "2.1.0",
        "eslint": "1.10.3",
        "eslint-config-airbnb": "^2.1.1",
        "eslint-plugin-react": "^3.11.3",
        "istanbul": "^0.4.2",
        "mocha": "2.3.4",
        "mocha-multi": "^0.7.2",
        "node-requirejs": "0.1.1",
        "sinon": "1.17.2"
    },

**Comment by gotwarlost** [comment]
You have probably installed `mocha` globally and that is the version that is being used for your tests. Provide a full path (from under `node_modules/`) to the `_mocha` executable in the `istanbul cover` command

i.e, something like
```
$ istanbul cover ./node_modules/.bin/_mocha --- etc.
```

**Comment by liz282907** [comment]
oh..i ran into the same problem, and i change the global mocha to the in-module _mocha executor ,however it doesn't work.
(in mac)
