### ISSUE TITLE
what modules make it into the report

### ISSUE THREAD

**Issue by tcurdt** [gotwarlost/istanbul#530]
I am a little confused on (and missing some documentation) on what gets instrumented and what ends up in the report and what not. The module loader should also load and instrument all dependencies - but only the files of my project show up in the report.

Would it be possible to include the coverage of some dependencies (from node_modules)?

**Comment by davglass** [comment]
By default `istanbul` ignores the `node_modlues` directory. You can include them by adding the `--no-default-excludes` flag to `istanbul cover`.

**Comment by tcurdt** [comment]
Ah! That would be a great addition to the docs.

I was looking at `istanbul help config` but it didn't list `node_modules`. In fact I only found `excludes: []`.

**Comment by gotwarlost** [comment]
`istanbul help cover` has this information.
