### ISSUE TITLE
HTML reporter exception

### ISSUE THREAD

**Issue by provegard** [gotwarlost/istanbul#536]
When I try to generate a HTML report, I get:

```
C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:241
            text = structuredText[startLine].text;
                                            ^

TypeError: Cannot read property 'text' of undefined
    at C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:241:45
    at Array.forEach (native)
    at annotateFunctions (C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:224:26)
    at HtmlReport.Report.mix.writeDetailPage (C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:427:9)
    at C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:489:26
    at SyncFileWriter.extend.writeFile (C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-writer.js:57:9)
    at FileWriter.extend.writeFile (C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-writer.js:147:23)
    at C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:488:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (C:\...\AppData\Roaming\npm\node_modules\istanbul\lib\report\html.js:482:23)
```

When this happens, startLine===21 and structuredText.length===11.

Other reporters work - cobertura, text, text-summary, teamcity. lcov doesn't work (same exception as above - in html.js) but lcov-text does.

What can be the cause of this? The input object contains full Windows paths to the instrumented files - I have tested changing backslashes to forward slashes as well as making the paths relative to the current directory (with and without leading dot-slash). Same error.

**Comment by provegard** [comment]
Never mind - the problem is that the coverage object doesn't refer to the uninstrumented files...

**Comment by gotwarlost** [comment]
yeah - that's the most common problem. The other reporters work because they don't actually have to look at the source code

**Comment by bchr02** [comment]
@provegard I get the same error:
> text = structuredText[startLine].text;

but I don't understand what you did to resolve it? Any help would be appreciated. Thanks.

Here is my coverage command: ```istanbul cover node_modules/mocha/bin/_mocha```

cc: @gotwarlost

**Comment by provegard** [comment]
@bchr02 Well I don't recall the details, but for some reason the coverage object contained the paths to the instrumented files rather than the uninstrumented/original files.

**Comment by suprise** [comment]
I have the same problem，but I still don't know how to resolve this problem after read this issue.Could you show me more clearer way to resolve this? @provegard thanks!

**Comment by wellnine** [comment]
The same issue.    @provegard   could you help us?

**Comment by wellnine** [comment]
I found where is an issue: it appears when I use:
`{
				test : /\.svg$/,
				loaders : [
					{
						loader : "babel-loader",
					},
					"svg-react-loader"
				]
			}`

**Comment by wellnine** [comment]
I switched from svg-react-loader   to   react-svg-loader. After that I removed the babel-loader from the chain and voila. It's working.
`			{
				test : /\.svg$/,
				loader : "react-svg-loader?es5=1"
			}`

**Comment by provegard** [comment]
@wellnine Based on that solution, I don't think we had the same problem. :)
