### ISSUE TITLE
Bring back the yellow color for "medium" coverage

### ISSUE THREAD

**Issue by JamesMGreene** [gotwarlost/istanbul#542]
After the recent redesign (#434, #439), the color scheme for "medium" coverage changed from a yellow theme (e.g. `#ffe87c`) to a gray/grey theme (e.g. `#eaeaea` & `#666`/`#666666`):

![image](https://cloud.githubusercontent.com/assets/417751/13084312/8dd6bb58-d49e-11e5-875c-d7e86528047c.png)

I think this change is confusing to consumers for a number of reasons, and possibly warrants restoring the old yellow theme.

To me, seeing the Gray color immediately made me think that something was **WRONG**, e.g.:
 - An error was thrown and prevented Istanbul from collecting all of its coverage
 - Something was incomplete
 - Something was disabled
 - Tests were skipped
 - `istanbul ignore` comments were used

However, after I stopped for a few minutes to dig through the Istanbul codebase (again), I discovered that is just the new color of choice for "medium" coverage. _Confusing!_

Some additional reasons why I'm pro-Yellow:
 - Green/Yellow/Red is a common color trio for many purposes that your average consumer is likely well-acquainted with:
     - Go/Caution/Stop (traffic lights)
     - OK/Warning/Error (common console/log reporting colors)
     - Calm/Caution/Danger, Growth/Sickness/Blood ([color symbolism](https://www.colormatters.com/color-symbolism/the-meanings-of-colors))

Would you consider changing the color scheme for "medium" coverage back to yellow-based?

I'd recommend using something a little lighter than the old background color (e.g. `#fff4c2`) to more closely align with the lightness of the current green and red background colors, and then using a darker yellow/gold to fill the need of the newly reflective chart-filling color (e.g. `#f9cd0b`).

Example screenshot:

![image](https://cloud.githubusercontent.com/assets/417751/13083029/e00e97c0-d498-11e5-99cf-f15281c577a2.png)

**Comment by JamesMGreene** [comment]
Ping @gotwarlost @davglass @tmcw

**Comment by davglass** [comment]
I'm :+1: on this change, @gotwarlost @tmcw are you two ok with it too?

**Comment by tmcw** [comment]
Yep, looks good to me!

**Comment by gotwarlost** [comment]
Could you submit a PR that I can merge? Sorry for the pedantry but I literally count the minutes that I have time to work on istanbul and would rather focus on getting a 1.x version out instead.

**Comment by JamesMGreene** [comment]
PR #597 seems to cover it as far as I can tell from my testing. :gift_heart:

**Comment by ZuBB** [comment]
While I am OK with change requested here and implemented in #597 I think this only partial solution.

I would like to suggest to move to old color scheme (and maybe styling). I am not against new flat design but imo old one has better contrast and more saturated colors better say where all is OK and where we have gaps.

see hacked screen below

![2016-06-08-155852_3840x1080_scrot](https://cloud.githubusercontent.com/assets/597016/15895087/06f05b92-2d92-11e6-9c96-83db2e0ef8b9.png)

guys, what do you think on this?
