### ISSUE TITLE
-x option would cause ReferenceError with mocha on travis-ci

### ISSUE THREAD

**Issue by jessy1092** [gotwarlost/istanbul#554]
My tests are in `specs` folder, so I exclude `specs` folder to run coverage.

```
istanbul cover -x specs/** node_modules/mocha/bin/_mocha -- specs --require specs/helpers/chai.js --reporter spec
```
I got `ReferenceError: describe is not defined` error.

[Test log](https://travis-ci.org/EasyIME/NIME/builds/112622424#L364)
P.S. This command worked well on `windows` but failed on `travis-ci`.

After I remove `-x specs/**`, all tests pase.
```
istanbul cover node_modules/mocha/bin/_mocha -- specs --require specs/helpers/chai.js --reporter spec
```
[Test log](https://travis-ci.org/EasyIME/NIME/builds/112623280#L364)

**Comment by gotwarlost** [comment]
It looks like the shell is expanding `specs/**` and istanbul is trying to run stuff under `specs/` diretcly.

Try putting single quotes around it. As in: `-x 'specs/**'`
