### ISSUE TITLE
Else path not taken

### ISSUE THREAD

**Issue by xaircore** [gotwarlost/istanbul#569]
There are a number of functions which not have else branch.  Considers covering but that is not covered else branch in which case
```
setEndDate: function(newDate) {
    if (this._setEndDate(newDate)) {
        this._notifyOnPropertyChanged('endDate');
        this._notify('onEndDateChange', this._options.endDate);
        this._notify('onDateRangeChange', this._options.startDate, this._options.endDate);
    }
}
```

**Comment by ljharb** [comment]
@xaircore have you tested a scenario where `this._setEndDate(newDate)` returns false? That's likely the "else path" it's complaining about.
