### ISSUE TITLE
Run istanbul cover with the file that was previously instrumented

### ISSUE THREAD

**Issue by epoberezkin** [gotwarlost/istanbul#576]
I am running `istanbul cover` command with the same file but with different command line arguments (it is a command line utility).

It is all working, each test generates its own report and they are all merged in the end.

The only problem is that for each test the same file is instrumented again and the tests run slowly.

I was trying to instrument the file once and pass instrumented file to `istanbul cover` but it doesn't seem to understand that the file is already instrumented and does it again.

Is there a way to use pre-instrumented file in `istanbul cover`?

**Comment by gotwarlost** [comment]
What is the instrumentation overhead (in terms of percentage of execution time, I mean)?

**Comment by epoberezkin** [comment]
Each test without coverage runs in less than 100ms, with coverage - depending on the environment from 1 to 2 sec. I will estimate which part is spent instrumenting and what is the increase in time actually running the code because it's instrumented.

**Comment by epoberezkin** [comment]
Running instrumented file is probably 1.3-1.5 times slower that the original code, but comparing it with the time it takes to instrument the code it's not that noticeable - instrumenting file takes approximately 90% of total test time. So being able to pre-instrument the file only once is likely to reduce the total tests time by the factor of 10.

**Comment by epoberezkin** [comment]
The solution is to use nyc with option `cache: true`. It also removes the need to merge the results of multiple processes - nyc does it automatically.
