### ISSUE TITLE
Exclude "set-up" code

### ISSUE THREAD

**Issue by pauldraper** [gotwarlost/istanbul#588]
```javascript
my.namespace.Class.prototype.method = function() {
  doStuff();
  moreStuff();
};
```

If this file is included in my test but `method` is never called, Istanbul tells me my code coverage is 33%, since the assignment counts at a statement/line. Semantically, my test coverage is more like 0%.

Most of my functions are rather short, and it's very hard for me to tell which files have some coverage, since all the function definitions add a non-trivial amount of coverage (10-20%) even in files having zero tests.

Three thoughts:

* Expand https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md, and allow annotations to fix htis.
* Allow me to hook into the syntax tree and tell Istanbul what not to include.
* Have a calibration run that just includes files but doesn't actually run tests. That can serve as a baseline for which lines are useful, and which are not.

**Comment by gotwarlost** [comment]
Sorry, this is how istanbul works. The act of `require`-ing the file executes the assignment. There is no way to change this.

**Comment by pauldraper** [comment]
It seems as if istanbul has gone to lengths to allow customization of what files and even parts of files are included in code coverage.

Am I reading this correctly that this situation is fundamentally different than these customizations?

**Comment by gotwarlost** [comment]
Yes. istanbul tracks coverage by adding variables that increment before every statement, function and so on. If a statement is executed, the corresponding variable is incremented and is the statement is reported as covered. The act of require-ing a file executes the mainline code in the module and thus counts those statements as covered. 

The customizations are for users to express the fact that a particular section of the code should not be penalized for lack of coverage; they are a reporting artifact and does not affect the main processing of how coverage works in principle.

What you are asking for is "don't increment coverage when I just require a file and only increment coverage for surrounding code when I actually execute the function as part of a test". istanbul has no way to know the difference between these 2 cases.

**Comment by pauldraper** [comment]
That makes sense.

I will probably write a script on my side that does my third idea: runs the set-up code only, and uses it as a baseline.
