### ISSUE TITLE
Support source maps for html report

### ISSUE THREAD

**Issue by jasonpincin** [gotwarlost/istanbul#59]
HTML report should support source maps. This would allow the reports to be far more digestible when running against browserify bundles (https://github.com/substack/node-browserify).

**Comment by XeCycle** [comment]
I vote on re-opening this, for support on languages compiling to js.

In my case I write in ECMAScript 6, and have my code transpiled by 6to5; the output code is still readable, yes, but it differs from the original code.

Anyway supporting source maps seems easier than supporting every language in the wild.

**Comment by arielschiavoni** [comment]
@XeCycle +1

**Comment by pascalduez** [comment]
Just a mere +1
ES(6|2015) transpilation is growing exponentially on projects, it would be great to be able to link to source code.

**Comment by alinex** [comment]
+1

**Comment by robertlevy** [comment]
+1

**Comment by lukeapage** [comment]
@gotwarlost are you seeing these comments?

+1
I am compiling using babel and would like to have the code coverage reports mapped to my input.

This also related to #308 - you could perhaps be clever and allow code that doesn't map back the input to not be marked as not covered?

**Comment by wojciak** [comment]
+1 Compiling typescript -> js

**Comment by acromarco** [comment]
+1 Compiling typescript -> js

**Comment by btesser** [comment]
+1 typescript -> js

**Comment by lukeapage** [comment]
This issue appears to now be covered by #212

**Comment by louy** [comment]
I was able to map back my coverage reports using source maps (I'm using typescript).
If anyone is interested, take a look at [this repo](https://github.com/urbanmassage/opool/).
Basically I'm just using [lcov-sourcemap by Tapad](https://github.com/Tapad/lcov-sourcemap). You'll want to look at files *package.json*, *scripts/map-coverage.js* and *circle.yml*.

**Comment by nmn** [comment]
Here's another great package for dealing with source maps: https://github.com/SitePen/remap-istanbul

**Comment by Izhaki** [comment]
For anyone interested in mapped coverage reports involving:

- Typescript
- Jasmine / Mocha
- tsc
- npm scripts

This may be of help:

# Output

![image](https://cloud.githubusercontent.com/assets/880132/16820312/4fe60e10-4948-11e6-8c5a-ddc9376d3918.png)

# Jasmine

See [https://github.com/Izhaki/Typescript-Jasmine-Istanbul-Boilerplate](https://github.com/Izhaki/Typescript-Jasmine-Istanbul-Boilerplate).

package.json (the relevant stuff):

    {
      "scripts": {
        "postinstall": "typings install dt~jasmine --save --global",
        "test": "ts-node node_modules/.bin/jasmine JASMINE_CONFIG_PATH=jasmine.json",
        "test:coverage": "ts-node node_modules/istanbul/lib/cli.js cover -e .ts  -x \"*.d.ts\" -x \"*.spec.ts\" node_modules/.bin/jasmine -- JASMINE_CONFIG_PATH=jasmine.json"
      },
      "devDependencies": {
        "istanbul": "^1.1.0-alpha.1",
        "jasmine": "^2.4.1",
        "ts-node": "^0.9.3",
        "typescript": "^1.8.10",
        "typings": "^1.3.1"
      },
    }

# Mocha

See [https://github.com/Izhaki/Typescript-Mocha-Istanbul-Boilerplate](https://github.com/Izhaki/Typescript-Mocha-Istanbul-Boilerplate).

package.json (the relevant stuff):

    {
      "scripts": {
        "postinstall": "typings install dt~mocha dt~require dt~chai --save --global",
        "test": "mocha --compilers ts:ts-node/register src/**/*.spec.ts",
        "test:coverage": "ts-node node_modules/istanbul/lib/cli.js cover -e .ts  -x \"*.d.ts\" -x \"*.spec.ts\" _mocha -- --compilers ts:ts-node/register -R spec src/**/*.spec.ts"
      },
      "devDependencies": {
        "chai": "^3.5.0",
        "istanbul": "^1.1.0-alpha.1",
        "mocha": "^2.5.3",
        "ts-node": "^0.9.3",
        "typescript": "^1.8.10",
        "typings": "^1.3.1"
      },
    }

**Comment by pygy** [comment]
With the 'instrument before bundling' approach, you need to build the project every time you want to get coverage data, even if you only touched the tests.

Having something like istanbul-remap builtin would be nice (for me as a user) as it would remove a moving piece of the setup.

@gotwarlost: Any chance you could at some point work with the SitePen/Dojo folks to upstream the [remap-istanbul](https://github.com/SitePen/remap-istanbul) core in Istanbul itself. It would solve #212 for all transpiled languages that support source maps (meaning, each and every serious one).

Pinging @kitsonk and @jdonaghue as well, upstreaming the core would allow you to ditch the various task runners and pre-processor plugins that you have to maintain.
