### ISSUE TITLE
Enhancement: Move remaining inline styles in HTML report to a separate CSS file

### ISSUE THREAD

**Issue by ChrisPearce** [gotwarlost/istanbul#593]
To allow the generated HTML reports to better comply with W3C Content Security Policy (CSP) specifications, it would be helpful to move the few inline styles within the generated HTML output to instead reference a separate CSS file.

**Comment by Srokap** [comment]
+1 this seem to break publishing HTML coverage reports on Jenkins due to default Content-Secuity-Policy https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy

**Comment by moos** [comment]
Problem isn't just with the inline-style, but also with the 'sandbox' CSP, since HTML publisher loads the report in an iframe:

```
Blocked script execution in 'https://<jenkins/Coverage_Report/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.inject 
```

**Comment by gigapixel** [comment]
+1
