### ISSUE TITLE
istanbul version 0.3.17 breaks CI, because console.error()

### ISSUE THREAD

**Issue by viktordavidovich** [gotwarlost/istanbul#606]
**Istanbul** version **0.3.17** breaks CI, namely TFS build, because inside **lib/collector.js**
**line 164** we have next code:

``` javascript
            if (cache.hasMappings()) {
                console.error('Post-processing using source maps');
                t = cache.transformer();
            }
```

Build breaks, because error exists. This is absolutely wrong, because post-processing using source maps is not error.
I've investigated, that inside newest version of Istanbul - everything is fine and console.log, console.error are not existing already there.

Just note, **DON"T PUSH DEV TOOLS TO THE PRODUCTION CODE!** 
You can break somebodies build :+1:

**Comment by fizker** [comment]
I would rather say that your CI setup is incorrect, if data on stderr breaks it. You should listen to exit codes instead.

Many *nix utilities (which is the inspiration for a lot of node tools) are using stderr as progress updates and the like. Take `curl` for example, where the data you are downloading goes to stdout and the progress updates go to stderr.

**Comment by mpalomas** [comment]
Unfortunately some (bad?) CI such as TFS have no setting for this: it's just the default behavior.

The workaround I use (for other tool such as Git) is to redirect stderr to stdout hoping it won't break anything. And soon a better workaround: just don't use TFS
