### ISSUE TITLE
instanbul and mocha mocha.opts

### ISSUE THREAD

**Issue by RusAlex** [gotwarlost/istanbul#614]
I do use mocha.opts file not in a `test` (default) directory mocha expect it to see. But with `--opts path/to/mocha.opts` flag for mocha testing. 

Istanbul does not work with mocha in this case.

**Comment by codekirei** [comment]
What is the exact command you are using to run istanbul?

**Comment by RusAlex** [comment]
Here is a full stack:

```bash
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --opts www/js/test-utils/mocha.opts www/js/test/ -- -R spec
No coverage information was collected, exit without writing coverage information
/usr/share/nginx/yii-version/www/js/test-utils/mocha.opts:1
(function (exports, require, module, __filename, __dirname) { --require www/js/test-utils/init.js
                                                                        ^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module.replacementCompile (/usr/share/nginx/yii-version/node_modules/append-transform/index.js:63:13)
    at Module._extensions..js (module.js:422:10)
    at Object.<anonymous> (/usr/share/nginx/yii-version/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/share/nginx/yii-version/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/share/nginx/yii-version/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/usr/share/nginx/yii-version/node_modules/mocha/lib/mocha.js:468:10)
    at Object.<anonymous> (/usr/share/nginx/yii-version/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Module.replacementCompile (/usr/share/nginx/yii-version/node_modules/append-transform/index.js:63:13)
    at Module._extensions..js (module.js:422:10)
    at Object.<anonymous> (/usr/share/nginx/yii-version/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at runFn (/usr/share/nginx/yii-version/node_modules/istanbul/lib/command/cover.js:126:16)
    at /usr/share/nginx/yii-version/node_modules/istanbul/lib/command/cover.js:146:9
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/lib/run-cover.js:187:16
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/lib/file-matcher.js:69:16
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:52:16
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:361:13
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:52:16
    at done (/usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:246:17)
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:44:16
    at /usr/share/nginx/yii-version/node_modules/istanbul-api/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1609:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by RusAlex** [comment]
My mocha.opts
```bash
--require www/js/test-utils/init.js
--compilers js:babel-core/register
--recursive
```

**Comment by codekirei** [comment]
Nice, thanks!  :+1:

You have `--opts` before `--`, so I'm pretty sure Istanbul is trying to interpret that flag and Mocha isn't seeing it (or the path to the test files) at all.

Try this:
```
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --opts www/js/test-utils/mocha.opts www/js/test/ -R spec
```

**Comment by RusAlex** [comment]
yes thank you very much. Could you explain what `--` means here ?

**Comment by codekirei** [comment]
Great! You're welcome :grin:

`--` is mentioned in the [readme](https://github.com/gotwarlost/istanbul#the-cover-command). It is also demonstrated by `help`:

```
> istanbul help cover

Usage: istanbul cover [<options>] <executable-js-file-or-command> [-- <arguments-to-jsfile>]
```

`--` is used to split up the CLI flags that are for `istanbul` and the flags that are for whatever application is running the tests (in this case, `_mocha`).

**Comment by namelus** [comment]
I'm on windows 7 home working through a Lynda.com course called Node.JS Essentials. When running:

`istanbul cover _mocha`

yields:

> C:\Lynda\Alex Banks - Nodejs Essential Training\Ex_Files_Nodejs_EssT\Exercise Files\Ch10\10_07\start
> >istanbul cover _mocha
> No coverage information was collected, exit without writing coverage information
> C:\Users\Suleman\AppData\Roaming\nvm\v7.4.0\_mocha.CMD:1
> (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
>                                                               ^
> SyntaxError: Invalid or unexpected token
>     at Object.exports.runInThisContext (vm.js:78:16)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\Suleman\AppData\Roaming\nvm
> \v7.4.0\node_modules\istanbul\lib\hook.js:109:37)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Function.Module.runMain (module.js:605:10)
>     at runFn (C:\Users\Suleman\AppData\Roaming\nvm\v7.4.0\node_modules\istanbul\lib\command\common\r
> un-with-cover.js:122:16)
>     at C:\Users\Suleman\AppData\Roaming\nvm\v7.4.0\node_modules\istanbul\lib\command\common\run-with
> -cover.js:251:17

I've looked online and they advise using istanbul@0.4.4 and did that. Another advice was to --save-dev. Did that as well; But to no avail.

here's my package json:

`{
  "name": "mocha-testing",
  "version": "1.0.0",
  "description": "Learn to write Unit Tests with Mocha Chai",
  "author": "Alex Banks",
  "license": "MIT",
  "keywords": [
    "Unit",
    "Testing",
    "Mocha",
    "Chai",
    "Rewire",
    "Sinon",
    "Supertest",
    "Cheerio"
  ],
  "devDependencies": {
    "chai": "^3.4.0",
    "istanbul": "^0.4.4",
    "nock": "^2.17.0",
    "rewire": "^2.3.4",
    "sinon": "^1.17.2"
  },
  "dependencies": {}
}`

Any advice?

Thanks in advance
Suleman
