### ISSUE TITLE
.istanbul.yml documentation

### ISSUE THREAD

**Issue by allantatter** [gotwarlost/istanbul#619]
#Is there anywhere a documentation for .istanbul.yml file and its configurable options?

**Comment by MitMaro** [comment]
You can get a fair bit of the information on the configuration from the the istanbul command. `istanbul help config` gives most of the information you will need, and descriptions for the options can usually be deduced from looking at the argument descriptions produced by `istanbul help <command>`.

**Comment by allantatter** [comment]
Thanks! It's not perfectly helpful way but at least it's something 😀
