### ISSUE TITLE
is project dead?

### ISSUE THREAD

**Issue by TrejGun** [gotwarlost/istanbul#624]

**Comment by mjilugu** [comment]
Can you provide description @TrejGun . I am seeing strange things with istanbul recently. It was working fine but now I get this:

`No coverage information was collected, exit without writing coverage information
/usr/local/bin/node:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^

SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runFn (/usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /usr/local/lib/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /usr/local/lib/node_modules/istanbul/lib/util/file-matcher.js:68:16
`

**Comment by mjilugu** [comment]
Can you provide details @TrejGun

**Comment by zachlysobey** [comment]
@mjilugu I think @TrejGun was asking if this project is "dead" or still being maintained. It looks like it *is* still being maintained? Although not very frequent updates?

Would be nice to get this issue closed ;-)

**Comment by davglass** [comment]
Yes, this project is still being maintained. @gotwarlost is a very busy person, but he's been actively working toward a `v1.0.0` release 😄

**Comment by gotwarlost** [comment]
Sorry, I haven't been paying attention to istanbul for some time now. I hope to pick it up in mid-June.
I apologize for all the delays.

**Comment by Roam-Cooper** [comment]
Thanks for the useful test coverage too. :)

**Comment by gotwarlost** [comment]
I'm going to start working on this with gusto starting in a couple of days...
