### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Kflash** [gotwarlost/istanbul#633]
Is this project dead?

**Comment by fizker** [comment]
Duplicate of #624

**Comment by graingert** [comment]
@gotwarlost it's late june now

**Comment by gotwarlost** [comment]
Yes, I'm working on it :) see https://github.com/istanbuljs/istanbul-lib-instrument/issues/4

**Comment by gotwarlost** [comment]
No. Maybe yes. Depends on your point of view. Stay tuned for some announcements soon.

**Comment by graingert** [comment]
![fawkesburngif](https://cloud.githubusercontent.com/assets/413772/16449677/b4d34f80-3df0-11e6-9977-66575c89bc5a.gif)
