### ISSUE TITLE
Cover command is being executed forever (nodejs 0.12, Ubuntu 12.04)

### ISSUE THREAD

**Issue by vitkarpov** [gotwarlost/istanbul#634]
I run the cover command:

```sh
$ ./node_modules/.bin/istanbul cover foo.js
```

... and seems the process just hangs, I can't get a result. Has anybody run into the same?

**Comment by vitkarpov** [comment]
I have figured out that Istanbul processes all files recursively in the current folder and subfolders. If a new folder will be created and `foo.js` will be there, than run cover from that folder works fine.

Seems weird that Istanbul processes all the files that it doesn't need to know about.

**Comment by gotwarlost** [comment]
This is a problem with the way the file match is implemented. Needs to be fixed.
