### ISSUE TITLE
Istanbul not working with jasmine-node on Win7

### ISSUE THREAD

**Issue by tschoartschi** [gotwarlost/istanbul#64]
We are using jasmine-node to test our server side code. Because we read in many blogs, that istanbul code coverage is awesome we wanted to give it a try. Therefore we installed istanbul. Jasmine-node runs fine and istanbul with karma (testacular) also runs fine. But combining jasmine-node and istanbul doesn't work for us on Windows 7 64bit. When we run the following command:

nodes_modules\.bin\istanbul.cmd cover node_modules\.bin\jasmine-node.cmd test/server/nmc/unit

We get: 
//-------------------------------------------------------------------------------------------------------------------------------
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
No coverage information was collected, exit without writing coverage information

SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (D:\Studium\DiplomArbeit\git\nomocom\protot
yping\to-scaffold\node_modules\istanbul\lib\hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (D:\Studium\DiplomArbeit\git\nomocom\prototyping\to-scaffold\node_m
odules\istanbul\lib\command\common\run-with-cover.js:88:16)
    at D:\Studium\DiplomArbeit\git\nomocom\prototyping\to-scaffold\node_modules\
istanbul\lib\command\common\run-with-cover.js:191:17
    at D:\Studium\DiplomArbeit\git\nomocom\prototyping\to-scaffold\node_modules\
istanbul\lib\util\file-matcher.js:52:16
    at D:\Studium\DiplomArbeit\git\nomocom\prototyping\to-scaffold\node_modules\
istanbul\lib\util\file-matcher.js:35:9
//-------------------------------------------------------------------------------------------------------------------------------

Running the same command on Ubuntu works fine and we get  a nice code coverage. On Ubuntu we use:

nodes_modules/.bin/istanbul cover node_modules/.bin/jasmine-node test/server/nmc/unit

Are we screwing something up, or is there a lack of compatibility with Win7? Does someone know how to fix this issue?

EDIT:
Our node version is: 0.10.5 and npm is on 1.2.18, if you need more information, let me know

Thank you
Tschoartschi

**Comment by dotnetCarpenter** [comment]
@MurFyahKapi thanks! This took me all day.

For **** sake puts this in **bold** in the [readme](../#readme)

**Comment by gotwarlost** [comment]
@dotnetCarpenter - care to submit a PR?

**Comment by dotnetCarpenter** [comment]
I need to do some more testing, just to be sure that it will also run on linux. But yes
