### ISSUE TITLE
istanbul cover: more than one command ?

### ISSUE THREAD

**Issue by rundef** [gotwarlost/istanbul#646]
Hi,
I have a projects who has two test frameworks :

- [Cucumber](https://www.npmjs.com/package/cucumber) for BDD tests
- [Mocha](https://www.npmjs.com/package/mocha) for unit tests

We're trying to use istanbul to calculate code coverage, but we aren't able to calculate both the unit tests coverage and bdd tests coverage at the same time.

**istanbul cover ./node_modules/.bin/mocha** works
**istanbul cover ./node_modules/.bin/cucumberjs** works
**istanbul cover ./node_modules/.bin/mocha ./node_modules/.bin/cucumberjs** doesn't work

From what I understand, the **./node_modules/.bin/cucumberjs** part is sent as command line argument to mocha.

Is there any way to make this work ?

Thanks

**Comment by davglass** [comment]
What I normally do is run the unit coverage and drop it into a `./unit` directory and then run the `bdd` tests and drop them into `./bdd`. Then use a script like this to generate the results for both:

```js
var istanbul = require('istanbul'),
    path = require('path'),
    collector = new istanbul.Collector();

    ['unit', 'bdd'].forEach(function(item) {
        var file = path.join(__dirname, item, 'coverage.json');
        collector.add(JSON.parse(fs.readFileSync(file, 'utf8')));
    });
        
    ['lcov', 'json'].forEach(function(type) {
        var report = istanbul.Report.create(type, {
            dir: path.join(__dirname, 'full')
        });
        report.writeReport(collector, true);
    });

```

**Comment by rundef** [comment]
Works perfectly, thank you @davglass
