### ISSUE TITLE
How to indicate which are the source files?

### ISSUE THREAD

**Issue by jcubic** [gotwarlost/istanbul#647]
I'm calling cli.js to generate the coverage using this command:
```
node_modules/istanbul/lib/cli.js cover node_modules/jasmine/bin/jasmine.js
```
it generate the coverage that look like this:

```
Statements   : 73.59% ( 2761/3752 )
Branches     : 56.08% ( 1089/1942 )
Functions    : 79.29% ( 448/565 )
Lines        : 73.81% ( 2759/3738 )
```
but my main source file that I'm testing have 5272 lines.

I've tried to put `preserve-comments: true` in `.istanbul.yml` file with no effect.

I have this in my jasmine spec file:

```javascript
if (typeof window === 'undefined') {
    var node = true;
    var jsdom = require("jsdom");
    global.document = jsdom.jsdom();
    global.window = global.document.parentWindow;
    var navigator = {userAgent: "node-js", platform: "Linux i686"};
    global.window.navigator = global.navigator = navigator;
    global.jQuery = global.$ = require("jquery");
    require('../js/jquery.terminal-src');
    require('../js/unix_formatting');
    global.location = {};
}
//tests
```

**Comment by gotwarlost** [comment]
Not sure what your question is. "Line count" is the count of lines that have executable statements, ignoring comments, blank lines and JS that is not executable. It is not a physical count of the lines in your code.
