### ISSUE TITLE
Update `fileset` dependency per https://nodesecurity.io/advisories/118

### ISSUE THREAD

**Issue by ntwb** [gotwarlost/istanbul#653]
The `minimatch` NPM module has been patched due to a regular expression denial of service:
- https://nodesecurity.io/advisories/118

- `istanbul` uses the `fileset` module which depends on `minimatch`

- There is a pull request to update `fileset` here: https://github.com/mklabs/node-fileset/pull/25

Once this is merged and a new release of `fileset` is released then a pull request can be created

**Comment by ntwb** [comment]
Minimatch 2.0.2 has now been released with this dependency update:

https://github.com/mklabs/node-fileset/compare/v1.0.1...v2.0.2

**Comment by use-strict** [comment]
Any updates here?

**Comment by nagustin** [comment]
Hi, is there any news on this?

**Comment by austinnichols101** [comment]
Bump.

**Comment by gotwarlost** [comment]
I've not had time to take a look and it is not a simple update since one of the tests fail and I need to figure out why. Will get to it soon,

**Comment by popomore** [comment]
fileset has always ignore node_modules https://github.com/mklabs/node-fileset/commit/c6593c09d6b998882ddf6232480a43c03f3a1a91

So this [testcase](https://github.com/gotwarlost/istanbul/blob/master/test/cli/test-cover-command.js#L167) failed.

**Comment by jonfreedman** [comment]
+1

**Comment by maxkoryukov** [comment]
Looks, like there is an overall solution: #673
