### ISSUE TITLE
Test coverage number too low when running test through interface instead of concert class 

### ISSUE THREAD

**Issue by jerrykwchan** [gotwarlost/istanbul#654]
Hi,

When run test through interface (I'm using typescript), the coverage number is too low.  It drops from 92% to 5%.  Is there any way to get the correct coverage number?

regards,
Jerry

**Comment by gotwarlost** [comment]
I don't understand what you mean. Could you elaborate?

**Comment by jerrykwchan** [comment]
Sorry, I found out that it is my problem.  I removed the interface and the test coverage number the same.  I guess either I missed some source file in instrumental call or the test file is not included.
