### ISSUE TITLE
No coverage information was collected in UBUNTU

### ISSUE THREAD

**Issue by Sachin077** [gotwarlost/istanbul#659]
Here is my full command:
node ./node_modules/istanbul/lib/cli.js cover --report cobertura --report html --hook-run-in-context -i ./_build\test\node_modules\vsts-task-lib\*.js ./node_modules/mocha/bin/_mocha _build/test/tasklib.js 

This command is for getting coverage reports of the Microsoft vsts-task-lib project (https://github.com/Microsoft/vsts-task-lib).

It works perfectly fine on windows and generates coverage reports. But on Ubuntu it shows "No coverage information was collected, exit without writing coverage information".

**Comment by gotwarlost** [comment]
Are you forking subprocesses in Ubuntu but not on windows? That would do it.

**Comment by Sachin077** [comment]
Got it! Just one more question, Is there any way I can know the dependency tree of a unit test? As in for a particular test, I want to know which functions did it run from the source code. Not just the line number, but the name of the method?

**Comment by gotwarlost** [comment]
No, istanbul doesn;t maintain this information.
