### ISSUE TITLE
if (false && true) return 'breaks'; highlights the rest of the file yellow

### ISSUE THREAD

**Issue by spearmootz** [gotwarlost/istanbul#668]
when testing if (false && true) {
}

where you dont test the true should highlight the && true never executed or something but it instead highlights the rest of the file as yellow

in this example its not so bad, but in when working on a big class where you test everything compleeeetely except for 1 function at the top where this happens then you end up with a whole class being highlighted in yellow.

**Comment by spearmootz** [comment]
![image](https://cloud.githubusercontent.com/assets/19737290/16886263/2265d484-4aa1-11e6-9bc8-c55382452333.png)

**Comment by gotwarlost** [comment]
You're using babel right? This is a babel source map bug.

https://phabricator.babeljs.io/T7453
