### ISSUE TITLE
Yet Another Istanbul Testing Question

### ISSUE THREAD

**Issue by Announcement** [gotwarlost/istanbul#679]
What is the proper way to use istanbul for es6 (babel?) with mocha.

Most answers I see recommend using things other than istanbul such as isparta or babel-istanbul, but I remember seeing mentioned somewhere that these are no longer needed...

My scripts must be run directly on the source without the compiling step please.

**Comment by jcollum** [comment]
>My scripts must be run directly on the source

why? This seems like an unnecessary requirement. Why not transpile and run coverage on that? Pretty easy that way. Looking around my node_modules folders, I see a lot of code like this: 

```
  "scripts": {
    "cover": "istanbul cover _mocha --report lcovonly",
    "coveralls": "npm run cover && istanbul-coveralls",

```

**Comment by gotwarlost** [comment]
Please check out `nyc` that may have the features you need. istanbul-the-command-line-tool is mostly dead now and will be officially (whatever that means) replaced with https://github.com/istanbuljs/nyc
