### ISSUE TITLE
Duplicate reports

### ISSUE THREAD

**Issue by designbyadrian** [gotwarlost/istanbul#769]
I recently moved a few files, and now in my coverage report, both the old and new locations are listed.

When trying to browse to the coverage report for the wrong locations, I get a page with a "Error: Unable to lookup source" error. Which is logical, as they don't exist!

I've searched my application for old references, but can't find any.

What other things should I consider when searching for a solution to my problem?

**Comment by designbyadrian** [comment]
Apparently, this is regarding Jest's implementation of Istanbul. I learned that the clean function didn't clear cache, so I ran:

`npm test -- --coverage --no-cache`

**Comment by nxmohamad** [comment]
This just helped me. Thank you for sharing it here @designbyadrian
