### ISSUE TITLE
No coverage information was collected, exit without writing coverage information

### ISSUE THREAD

**Issue by dschinkel** [gotwarlost/istanbul#798]
I've spent hours on this.  Cannot get past this infamous error.

https://github.com/dschinkel/we-do-tdd-service

I'm running this which runs fine in terms of the test passing, but immediately after the test passes I get that error still:

```
npm run build && ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha \"./dist/test/**/*.spec.js\" --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf coverage
```

You can clone it and just try `npm run coverage` to see the error.

Just makes no sense to me why this would not work.  I want this to work without resorting to babel-node or babel-instanbul

UPDATE
--------

this works but I had to cd into my dist/test directory first for some reason.  I'd like not to have to do that, and to get the first working.  Thoughts?

``` 
npm run build && cd ./dist/test && istanbul cover ../../node_modules/.bin/_mocha \"./**/*.spec.js\" --report lcovonly -- -R spec && cat ./coverage/lcov.info | ../../node_modules/coveralls/bin/coveralls.js && rm -rf ../../coverage
```

**Comment by dschinkel** [comment]
resolved, there was something wrong with my path for my test file.  When I moved the test file to root and change my script to look for the .spec.js in root it worked so....that's what it was.  It's weird because that path to dist/test did run my tests, mocha did run it, but for some reason, istanbul didn't like that path for whatever reason, it couldn't report coverage on dist/test

**Comment by LanmeijingLucky** [comment]
Moving the test.js file on root,  it worked

```
 istanbul cover _mocha t_1.js
```
