### ISSUE TITLE
How to integrate test coverage with SonarQube

### ISSUE THREAD

**Issue by kopax** [gotwarlost/istanbul#801]
I am using [SonarQube](https://sonarqube.com/) for integrating my test in my build process.

I've seen there is a [sonnar-scanner](https://github.com/bellingard/sonar-scanner-npm) npm package but I don't see how it re-use the code coverage from jest/istanbul.

Anyone has experience with SonarQube and istanbul ?

**Comment by adam-moss** [comment]
You'll want to create a `sonar-project.properties` file with relevent content:

```sonar.projectKey=<<unique project key>>
sonar.projectName=<<freetext project name>>

sonar.language=js
sonar.sources=relative/path/to/src
sonar.tests=relative/path/to/tests

sonar.javascript.lcov.reportPaths=path/to/coverage/lcov.info```

Then you can simply run `sonar-scanner` directly.

**Comment by biswasaveek** [comment]
@adam-moss That's correct. Sonarqube is showing the coverage numbers after passing the "sonar.javascript.lcov.reportPaths" argument. 
However, many files, which are excluded in the istanbul cover command are also showing up in the sonarqube dashboard. Consequently, the total LOC is higher and coverage number is lower in the sonarqube dashboard.

**Comment by bcass** [comment]
@biswasaveek Specify any files you want to exclude using `sonar.exclusions`

E.g. `sonar.exclusions=**/*Bean.java,**/*DTO.java`

Source: https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus

**Comment by stantoncbradley** [comment]
`sonar.exclusions` and `sonar.tests.exclusions` doesn't seem to do anything for me
https://stackoverflow.com/questions/47913557/sonarqube-with-jest-unit-tests

**Comment by sasikumar25** [comment]
In my case istanbul is generating a report in html format. How could i convert a html report to lcov file formt

**Comment by craigtmoore** [comment]
Take a look at their github site:
https://github.com/istanbuljs/nyc

From site:
> Configuration arguments should be provided prior to the program that nyc is executing. As an example, the following command executes npm test, and indicates to nyc that it should output both an lcov and a text-lcov coverage report.
> 
> nyc --reporter=lcov --reporter=text-lcov npm test

**Comment by VikashChoudahry** [comment]
> In my case istanbul is generating a report in html format. How could i convert a html report to lcov file formt ?

Please follow the below steps to achieve this:

1. Run the test by running the same command which `craigtmoore` has mentioned, which is,
    nyc --reporter=lcov --reporter=text-lcov npm test
2. Once step 1 is completed, you must be seeing a file named as `lcov.info`
3. Add below property in `sonar-project.properties` file,
    # coverage reporting 
    sonar.javascript.lcov.reportPaths=app/coverage/lcov.info

    **Note:** For more details please refer 
    `https://docs.sonarqube.org/display/PLUG/JavaScript+Coverage+Results+Import`
4. Run the `sonar-scanner` command from your project root directory.

**Result**: You must be seeing the code-coverage %age in the generated report by Sonarqube.

Please do comment if still, you're facing the issue.
Thanks

**Comment by amiya-elear** [comment]
i change sonar-project.properties sonar.javascript.lcov.reportPaths=app/coverage/lcov.info, but its not reflecting in my sonarqube dashboard. can anyone can help me .

**Comment by shaktikumardelhi** [comment]
Same problem as "Amiya-elear" mentioned.

**Comment by cbartram** [comment]
Try adding the `-X` flag to the ` sonar-scanner` command it will print debug info which will help you pinpoint why its not picking up your lcov file. You can search the logs with `command + f` for "lcov" sonar will often times print warnings that it cant find the path to the file which is more than likely the problem

**Comment by thanh3d** [comment]
> > In my case istanbul is generating a report in html format. How could i convert a html report to lcov file formt ?
> 
> Please follow the below steps to achieve this:
> 
> 1. Run the test by running the same command which `craigtmoore` has mentioned, which is,
>    nyc --reporter=lcov --reporter=text-lcov npm test
>    **For more details:** Please refer (https://github.com/istanbuljs/nyc)
> 2. Once step 1 is completed, you must be seeing a file named as `lcov.info`
> 3. Add below property in `sonar-project.properties` file,
>    sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
>    **Note:** For more details please refer
>    (https://docs.sonarqube.org/display/PLUG/JavaScript+Coverage+Results+Import)
> 4. Run the `sonar-scanner` command from your project root directory.
> 
> **Result**: You must be seeing the code-coverage %age in the generated report by Sonarqube.
> 
> Please do comment if still, you're facing the issue.
> Thanks

thanks, it help me a lot !

**Comment by loveujindagi** [comment]
do we need any plugin in sonar to publish instanbul coverage report.

**Comment by VikashChoudahry** [comment]
As per my understanding, no additional plugin is required. As I have mentioned above I have followed the same steps to integrate the coverage in the SonarQube app.

**Comment by cmacdonnacha** [comment]
> @biswasaveek Specify any files you want to exclude using `sonar.exclusions`
> 
> E.g. `sonar.exclusions=**/*Bean.java,**/*DTO.java`
> 
> Source: https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus

I know this was posted a few years ago but I'm a bit confused as to why we need to specify `sonar.exclusions` when we have already excluded those files in the Istanbul report? I don't see much point having to have exclusions in 2 places.

**Comment by swissarthurfreeman** [comment]
> 

For the users with perverse fonts in their browsers, it is lcov with l as in lego or lol. Not I.
