### ISSUE TITLE
Code coverage miss when using window.location.href

### ISSUE THREAD

**Issue by prajapati-parth** [gotwarlost/istanbul#863]
I encountered a strange issue where I was trying to cover a function in react class that was of the following kind
```jsx
class xyz extends React.Component {
  doRedirect() {
    // other code
    const url = '/456'
    window.location.href = url;
  }
}
```
Trying to hit the code doesn't work. But commenting out the line `window.location.href = url` hits the code.

**What I've tried so far:**
I thought accessing `window` might throw an exception but doing `console.log(window)` it logs a window object.

**Comment by zivyangll** [comment]
+1

**Comment by zivyangll** [comment]
@prajapati-parth I also encountered this problem, how did you solve it?

**Comment by prajapati-parth** [comment]
@zivyangll I do not exactly remember as this has been like an year ago but looking at the git history it seems like I changed `window.location.href = "https://some.url.com"` to `window.location.assign("https://some.url.com")`.
