### ISSUE TITLE
mocha Illegal Token Error

### ISSUE THREAD

**Issue by anderslyman** [gotwarlost/istanbul#90]
I'm on Windows 8.
I have a spec folder containing a single test file, and when I run:

`istanbul cover _mocha -- -R spec`

Inside that folder, I get:

```
C:\Users\alyman\AppData\Roaming\npm\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0
                                                              ^
No coverage information was collected, exit without writing coverage information
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (C:\Users\alyman\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (C:\Users\alyman\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:86:16)
    at C:\Users\alyman\AppData\Roaming\npm\node_modules\istanbul\lib\command\common\run-with-cover.js:189:17
    at C:\Users\alyman\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:52:16
    at C:\Users\alyman\AppData\Roaming\npm\node_modules\istanbul\lib\util\file-matcher.js:35:9
```

**Comment by EvanHongYousan** [comment]
it works ,thank you! @gotwarlost

**Comment by DevinXian** [comment]
Thank you, it works!

**Comment by iongion** [comment]
Using windows **10**
Using node **v5.7.0**
Using istanbul **0.4.3**
Using mocha **2.4.5**

No cygwin, no mingw, no linux emulation, plain old Windows with bat and cmd files
I've tried:
```
node_modules\.bin\istanbul cover --hook-run-in-context _mocha --compilers js:babel-core/register --bail --sort --reporter dot --require .\test\bootstrap.js --recursive test/unit/**/**/*.spec.js
```

I get:
```
No coverage information was collected, exit without writing coverage information
C:\Users\me\AppData\Roaming\npm\_mocha.CMD:1
(function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Object.Module._extensions.(anonymous function) [as .js]
```

**Comment by iongion** [comment]
In the end it is working, like this:

```
node_modules\.bin\babel-node.cmd ./node_modules/istanbul/lib/cli cover node_modules/mocha/bin/_mocha -- --compilers js:babel-core/register --bail --sort --reporter dot --require test/bootstrap.js --recursive test/unit/**/**/*.spec.js
```

**Comment by legendtang** [comment]
Still encounter this issue.

Using Windows 10
Using node v6.1.0
Using istanbul 0.4.3
Using mocha 2.5.3

**Comment by xunshicheng** [comment]
i do like below, it works:
npm install mocha， not add -g; 
then $ istanbul cover node_modules/mocha/bin/_mocha

**Comment by bennyn** [comment]
I am on Windows 10 and installed "istanbul" globally (v0.4.5). My "npm test" script looks like this:

```json
"test": "istanbul cover node_modules/mocha/bin/_mocha -s 30000 -t 30000 --recursive test/harness.js test --trace-warnings"
```

When I am running `npm test` I am getting this exception:

```bash
> istanbul cover node_modules/mocha/bin/_mocha -s 30000 -t 30000 --recursive test/harness.js test --trace-warnings

No coverage information was collected, exit without writing coverage information
D:\dev\projects\wireapp\proteus.js\node_modules\mocha\lib\utils.js:634
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) '30000'
    at Object.lookupFiles (D:\dev\projects\wireapp\proteus.js\node_modules\mocha\lib\utils.js:634:15)
```

Can you help me with this?

**Comment by bennyn** [comment]
Note: I also got a similar issue when running `istanbul` together with `jasmine`:

> istanbul cover --report html jasmine
> No coverage information was collected, exit without writing coverage information
> D:\dev\projects\wireapp\wire-web-packages\packages\cryptobox\node_modules\.bin\jasmine.CMD:1
> (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (

What I needed to do is change:

```bash
istanbul cover --report html jasmine
```

To:

```bash
istanbul cover --report html ./node_modules/jasmine/bin/jasmine.js
```

**Comment by FrankChinedu** [comment]
> istanbul cover _mocha

No coverage information was collected, exit without writing coverage information
/home/frank/Documents/andela/ALC/book_a_meal/back/test/meals.test.js:1
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                                     ^^^^

SyntaxError: Unexpected identifier

**Comment by FrankChinedu** [comment]
> istanbul cover _mocha

No coverage information was collected, exit without writing coverage information
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                                                                             ^^^^

SyntaxError: Unexpected identifier

**Comment by FrankChinedu** [comment]
> istanbul cover _mocha

No coverage information was collected, exit without writing coverage information
(function (exports, require, module, __filename, __dirname) { import chai from 'chai';
                                                                                                                                                            ^^^^

SyntaxError: Unexpected identifier
