### ISSUE TITLE
Transformation error; return original code. Unexpected token ...

### ISSUE THREAD

**Issue by chuksynaza** [gotwarlost/istanbul#904]
After trying to merge objects in my code using:

 `this.config = { ...defaultConfig, ...config };`

I get the error:

Transformation error; return original code

Unexpected token ...

And test coverage is not reported for that file. If that line is commented then test coverage is reported and the error goes away.

**Comment by jcollum-nike** [comment]
Same here. My version is `"istanbul": "^0.4.5",`

**Comment by chuksynaza** [comment]
This package is now deprecated and doesn't support ES6. Use [nyc - instanbul.js.org](https://istanbul.js.org/). It works with the [babel-plugin-instanbul](https://github.com/istanbuljs/babel-plugin-istanbul) and has full class support for ES6.

It is also very easy to setup

`$ npm install --save-dev nyc`

Then in your package.json

```json
{
  "scripts": {
    "test": "nyc mocha"
  }
}
```
Happy coding :smile:

**Comment by jcollum-nike** [comment]
It would be helpful if that deprecation warning was right at the top of the readme, along with this suggestion for an alternate.

**Comment by asirihewage** [comment]
Anyway can we get automation coverage using nyc?
 I know we could get it using Istanbul.

**Comment by chuksynaza** [comment]
@abejfehr just so I'm not lost, what do you mean by automation coverage?
