### ISSUE TITLE
Coverage Report Table has alignment issues on Terminus Terminal

### ISSUE THREAD

**Issue by JamieCorkhill** [gotwarlost/istanbul#916]
I submitted this issue on the Jest Repository regarding the rendering of the coverage table but was told to post it here instead.

The issue is that on the Terminus Terminal for Windows, the columns of the generated table are not correctly aligned. They are correctly aligned, however, on the VS Code Integrated Terminal.

See [here](https://github.com/facebook/jest/issues/8646) for more details.

Thanks.

**Comment by SimenB** [comment]
This repo is deprecated, you should file at https://github.com/istanbuljs/istanbuljs

**Comment by JamieCorkhill** [comment]
@SimenB Thank you. Indeed, I had seen that the repo was deprecated, but I couldn't find the link to the active repo. Since the latest issue was from 18 hours ago (or so), I figured people were still posting here.

Anyway, I'll file it over there and thanks for the quick turnaround.
