### ISSUE TITLE
visually identifying vendor vs my code

### ISSUE THREAD

**Issue by Raynos** [gotwarlost/istanbul#92]
I do not want to exclude vendor modules as I find it interesting to see how much coverage is however I want a way to mark this code coverage as less important critical.

Maybe in the UI of html coverage it can be shown as two tables one for my code and one for my vendor code.

My personal use case is that I have a ./lib folder that contains generic code that will go into npm at some point in the future. It doesnt need full coverage because its not the responsibility of my current app / module to test it (it needs its own seperate unit test suite)

However I'm still interested in seeing how much of that generic code I use to get an idea about whether I have over engineered that code / made it too generic.

**Comment by silkentrance** [comment]
@Raynos please come up with your own tool for that very specific use case.

@gotwarlost please close as it is definitely not in istanbul's scope.
