### ISSUE TITLE
Istanbul and moch help

### ISSUE THREAD

**Issue by 7h3kk1d** [gotwarlost/istanbul#93]
I'm almost positive I'm just doing something wrong. I'm attempting to use mocha unit tests along with istanbul for code coverage.

I use the command istanbul cover mocha the tests pass but the following is displayed from istanbul:
"No coverage information was collected, exit without writing coverage information"

Any help would be much appreciated or redirecting me to where help would be more appropriate.

**Comment by didoChulz** [comment]
I'm new to this category. I want to use mocha with istanbul to use as the code coverage tool.But I'm unable to make it work. can anyone help me to guide me in to a good tutorial
