### ISSUE TITLE
Content-Security-Policy unsafe-eval

### ISSUE THREAD

**Issue by tudorgergely** [gotwarlost/istanbul#932]
Hi!

I have an issue with istanbul __coverage__ object on window and our CSP. The coverage report is working great locally but we also want to instrument an app we deploy to a certain environment. 

We don't allow unsafe-eval in our CSP and because the instrumenter uses `Function()` it fails our CSP: https://github.com/gotwarlost/istanbul/blob/bc84c315271a5dd4d39bcefc5925cfb61a3d174a/lib/instrumenter.js#L692

Is it possible to get around or fix this? Do you have alternatives to Function() in this case?

Thank you!

**Comment by praveen7557** [comment]
hey @tudorgergely, were you able to fix this?
