### ISSUE TITLE
Open Coverage File Automatically on Test Command?

### ISSUE THREAD

**Issue by tracyalison11** [gotwarlost/istanbul#939]
Is there any configuration setting that serves or pops open the coverage file in a browser window? I am looking for a solution to have it open up on command instead of digging for the file and opening static html. Thanks so much for any direction on this and thanks for writing this package! Huge help to our team.

**Comment by mannyluvstacos** [comment]
Hey there @tracyalison11!
If you're using npm or yarn, would calling
```bash
test: [incantations of all the testing and covering] && open coverage/lcov-report/index.html
```
not work?

Or even have a script such as:
```json
"openCoverage": "open coverage/lcov-report/index.html"
```
And calling `npm run openCoverage` or `yarn openCoverage` work?

**Comment by tracyalison11** [comment]
Thank you so much! Implemented this and it works!
