### ISSUE TITLE
Covering Child Processes or Merging Results

### ISSUE THREAD

**Issue by AdrianSchneider** [gotwarlost/istanbul#97]
Is it possible to capture coverage from child processes, or perhaps merge multiple coverage reports together?

I'm testing a small application which acts as a service in a larger SOA system. I have my code coverage working properly for unit tests, and I am very happy with the results. Everything is tested very granularly (all dependencies, including external-reaching ones like request, httpreq/httpres). Code coverage is fairly accurate.

I also have some very basic acceptance tests to ensure the application is wired together properly, and basic functionality works. The test spawns some child processes (a webserver simulating the feed it consumes, and a worker to consume it) and performs some very basic assertions. Unfortunately, I lose almost all coverage possibilities here because the acceptance test doesn't actually do anything but spin up other applications. I find this coverage valuable because it checks the wiring & real implementations of http requests, database queries, etc. that I cannot get (and do not want) from unit tests.

Any suggestions or ideas would be very helpful.

Thanks!

**Comment by ORESoftware** [comment]
Just a thought, since Istanbul is CPU intensive, best/easiest thing to do might be to generate a bash script like so:

```
istanbul cover foo1.js --dir ./coverage/dir1
istanbul cover foo2.js --dir ./coverage/dir2
istanbul cover foo3.js --dir ./coverage/dir3
istanbul cover foo4.js --dir ./coverage/dir4

istanbul report
```

since as far as I understand there's no real reason to run them in parallel, running them with bash is straightforward.
